### ISSUE TITLE
mapper 413 info I found

### ISSUE THREAD

**Issue by hossbags2** [TASEmulators/fceux#269]
https://github.com/MiSTer-devel/NES_MiSTer/commit/3657add72d90f8983b344954e8c8a5b00a32a003

**Comment by ClusterM** [comment]
Can you send me ROM for testing? clusterrr@clusterrr.com

**Comment by hossbags2** [comment]
I sent an email to you from hossbags2

**Comment by ClusterM** [comment]
Thank you, i'll try to implement this mapper soon.

**Comment by hossbags2** [comment]
cool....thank you sir!!!

**Comment by negativeExponent** [comment]
@ClusterM did you happen to try to implement this mapper 413? i've dont this for Mesen and it works great. but for whatever reasons i can get the PCM audio to work right for fceux.

**Comment by ClusterM** [comment]
It's on my to-do list... but it's on the bottom of my to-do list :(

**Comment by negativeExponent** [comment]
@ClusterM sorry to bother. i seem to find issue with regard to wrong PCM value. it appears that serial reads are dont faster than it should, like 4 time on the same address. ive implemented a similar fix with MMC1 and this seems to work at least for the few beginning samples!

```
static uint64 lreset;
static DECLFR(M413ReadPCM) {
	uint8 ret = X.DB;
	if ((timestampbase + timestamp) < (lreset + 4)) {
		return ret;
	}
	if (serialControl & 0x02) {
		ret = ROM.misc.data[serialAddress & (ROM.misc.size - 1)];
		serialAddress++;
	} else {
		ret = ROM.misc.data[serialAddress & (ROM.misc.size - 1)];
	}
	lreset = timestampbase + timestamp;
	return ret;
}
```

maybe you have a better idea or why CPU reads seems to happen faster than it should.

**Comment by hossbags2** [comment]
I am not sure, I just know the game does not work

**Comment by ClusterM** [comment]
> maybe you have a better idea of a fix or why CPU reads seems to happen faster than it should.

Can you share your fceux branch with mapper 413 support? I'll try to debug it. 

Too sad that this mapper is not documented on wiki.nesdev.org yet.

**Comment by negativeExponent** [comment]
> > maybe you have a better idea of a fix or why CPU reads seems to happen faster than it should.
> 
> Can you share your fceux branch with mapper 413 support? I'll try to debug it.
> 
> Too sad that this mapper is not documented on wiki.nesdev.org yet.

heres the branch with misc roms area support and mapper 413
https://github.com/TASEmulators/fceux/issues/269#issuecomment-1880033178

**Comment by ClusterM** [comment]
Sorry for such late answer, was busy. It works perfectly for me, I can't see any issues in the sound.

**Comment by hossbags2** [comment]
The only game that uses mapper 413 is Super Russian Roulette and I just tried it. It says it does fceux does not support the mapper at all.Sent from my T-Mobile 5G Device
-------- Original message --------From: Alexey Cluster ***@***.***> Date: 1/18/24  7:49 AM  (GMT-05:00) To: TASEmulators/fceux ***@***.***> Cc: hossbags2 ***@***.***>, Author ***@***.***> Subject: Re: [TASEmulators/fceux] mapper 413 info I found (#269) 
Sorry for such late answer, was busy. It works perfectly for me, I can't see any issues in the sound.

**Comment by hossbags2** [comment]
The only game that uses mapper 413 is Super Russian Roulette. The emulator says it does not support mapper 413 at all at this time. Doss not load.

**Comment by ClusterM** [comment]
> The only game that uses mapper 413 is Super Russian Roulette. The emulator says it does not support mapper 413 at all at this time. Doss not load.

> heres the branch with misc roms area support and mapper 413 https://github.com/negativeExponent/fceux/tree/mapper413
