### ISSUE TITLE
Debugger Step Back feature and GUI improvement

### ISSUE THREAD

**Issue by Chipsum** [TASEmulators/fceux#352]
Hi

I believe it's time that FCEUX debugger gets new features and overall GUI improvement.

I would like to suggest but Mesen's Debugger has said it all.

Also Step Back implementation would be appreciated.

![image](https://user-images.githubusercontent.com/37517008/118792218-5a50a200-b88f-11eb-9ca2-4084bd162cd2.png)

**Comment by mjbudd77** [comment]
I've started making some changes to the debugger layout to save space. I added a tool bar and moved most of the buttons and check boxes to either menu or tool bars. Someone has requested to have the bookmark area be as big as possible. In looking at the Mesen debugger window, I see a lot of stuff that I'm not sure the FCEUX core has hooks for. But I can still try to improve the overall debugger usability. I could use some feedback and ideas on what I've done so far.
Regarding the step back feature of Mesen, I looked at the documentation and it does not describe how this works. Does it just move program counter back to the previous instruction OR does it restore the entire state of the emulation back to what it was a the previous instruction (ie load a saved state)? How does it work with branches and jumps in the code, does it keep a history of last run instructions so that it knows where to go? How big would this history be?

**Comment by Chipsum** [comment]
@mjbudd77 
Happy to hear that,
In fact not all options from Mesen's debugger are the most wanted, so maybe I will toss some of what most debuggers needs:
- Basic GUI elements: Nice font (like Consolas), colors, ability to select and copy, highlight verified code in green ..etc 
- Yep bookmarks are extremely helpful (instead of writing which PC address to store to experiment it.Mesen does have this idea of labels which is good, but it's better to have it in a list and or some sort of easy jump bookmark and search ability.
- Step back (only for instructions), it doesn't matter to step back the whole state, just the instructions (with registers and stats accordingly of course).

Bookmarks, labeling, save things, must be really flexible to use since it's the most haunting thing in debugging along with step back (which really helped a loooooooot thanks to Mesen).

**Comment by mjbudd77** [comment]
I'm trying to understand why fceux has bookmarks and debug symbols separate. What if I displayed a debug symbol viewer on the window? Would the bookmark view still be needed?

**Comment by bbbradsmith** [comment]
Mesen does step back the entire state. I'm not sure how it would be useful at all otherwise?

**Comment by vadosnaprimer** [comment]
> Mesen does step back the entire state. I'm not sure how it would be useful at all otherwise?

Since rewind is always consecutive, it is all delta states. And if we keep tracelog info in memory in some efficient form, that's all the data we need if we want to rewind one instruction. FCEUX already tells current value of whatever memory addresses are affected by the instruction to be executed, so even by parcing textual tracelog it's theoretically possible to restore everything needed for rewinding. But that's probably less efficient than reading it from an in-memory representation (array of structs?) than from a string.

Keep savestates of all instructions won't be efficient at all.

**Comment by mjbudd77** [comment]
This mechanism of storing data arrays is how I implemented the trace logger for the Qt GUI. I would only need to add a couple more parameters to have everything I need to reverse instructions. But this won’t be usable in the win32 version without moving it to the core. I would still need to write a function that undoes each opcode as well

**Comment by vadosnaprimer** [comment]
Since win32 is to-be-deprecated, it'd probably be enough to only have it in Qt for now.

**Comment by mjbudd77** [comment]
I've made a lot of changes to the development version of the Qt debugger window. I could use some feedback from those interested. I also have questions:

- For the PPU status display. How important is it? The PPU status on the mesen debugger window takes up alot of space. How useful is that? Should I consider something similar in fceux?
- I am considering creating a debug symbol table viewport on the debugger window. Something like a tree view grouped into bank pages. Is this something that would be useful?

**Comment by vadosnaprimer** [comment]
I think it's easy enough to handle symbol names in the text file directly. Dunno about others.

**Comment by Chipsum** [comment]
PPU stats at least the basic ones (cycles, scanlines).
debug symbols are not that important to make them in a list, I'd rather prefer to see them as a popup to reduce consuming form's space.
I will give my opinion of the new changes, I know it's in early stage, but why not:
![image](https://user-images.githubusercontent.com/37517008/125092549-5c81f080-e0c9-11eb-995d-2698e06bb97c.png)

The part to the left is the most thing I hated about Fceux, we need ASM instructions in colors, direct memory call in another color, ...etc.
So:

- Apply a color system to the disassembly part.
- I suggest a slight increase in font, maybe change font to Consolas too, it's an amazing font for that.
- Add basic context menu features (copy selected code):
![image](https://user-images.githubusercontent.com/37517008/125093068-e0d47380-e0c9-11eb-9fc3-bcf238da2ce4.png)

- Search bar, to search either for labels (if there will be a labeling system), or for any value or a comment.
- I suggest hotkey CTRL+F for search and CTRL+G rather than P for Goto, I dunno I find it more practical.
- Add Background coloring for lines like (verified code, ..etc).
- Right click on a line from a routine to edit the code (with the ability to save changes to ROM, or to loose them if emulation is reset).
- And please please please, the window is really hard to display it completely, If I resize it gets overflown with low resolutions.

I really want to see the visual changes especially colors and font.

**Comment by mjbudd77** [comment]
I added a font selection option to the Qt GUI. You can now choose any monospace font installed on your system.  Also, I'm pretty sure that anytime you highlight text in the assembly viewer, I already have that text being copied to the system clipboard. I will see what I can do about the coloring system.

**Comment by Chipsum** [comment]
@mjbudd77 
https://drive.google.com/file/d/16M87-GFC3O_PcKAc8DDrwLR4NJnm_LNv/view?usp=sharing

**Comment by mjbudd77** [comment]
@Chipsum , I’ve made some more layout changes that I think will help you. Just curious, what resolution is your desktop using?

**Comment by Chipsum** [comment]
@mjbudd77 
In fact that's true, I use a lower resolution 1270x720, I use a big screen far away from me, and I can't see anything without difficulty in higher resolutions.
I will check the changes and see, maybe I did not notice the overflow since I used Mesen a lot and never had a problem with the layouts.

**Comment by mjbudd77** [comment]
![Screenshot from 2021-07-14 07-04-00](https://user-images.githubusercontent.com/44712797/125612035-4ce2597c-6469-4c2b-96cd-08a0ce0cd75c.png)
I'm adding a frame to the Qt debugger that displays the PPU control and mask register state. The mesen debugger uses check boxes to show the decoded bit values of the registers. This seems to take up a lot of space in the window. Is this preferred?
I could just show the hex value of the register and it would be a lot more compact.
If decoding the bits is important, I could make a tool tip popup that shows the decoded values, but it would have to be hovered over by mouse to trigger it. What is the best way to proceed?

**Comment by mjbudd77** [comment]
@Chipsum I came up with a new tabbed window approach for the Qt GUI debugger. All tabs are able to be relocated either via window menu presets (as seen in View -> Layout), context menus (via right click on tab), and/or drag n drop (via left click hold/drag). Please provide feedback.

**Comment by Chipsum** [comment]
Amazing, I love it
Now the layout is flexible, I can resize it that's great
![image](https://user-images.githubusercontent.com/37517008/126063565-61e2bdab-8bf9-4d7f-912b-4185d8480ab4.png)
I will test it for a while and I will provide a feedback.

**Comment by mjbudd77** [comment]
@Chipsum , its been a while. Do you have any feedback on this?
