### ISSUE TITLE
Dragon Ball - Daimaou Fukkatsu (does not compute)

### ISSUE THREAD

**Issue by Chipsum** [TASEmulators/fceux#383]
it doesn't run on Fceux (on any version)
it does somehow run on Mesen, but still buggy.
![image](https://user-images.githubusercontent.com/37517008/124362154-44265780-dc2b-11eb-91a6-294a1281f405.png)

Used Rom:
```
Database match: Dragon Ball - Daimaou Fukkatsu (Japan)
Database: No-Intro: Nintendo Entertainment System (v. 20210216-231042)
File SHA-1: FF9A24473DCCCD96D9F8AD38E3004E674B8C87C9
File CRC32: A3F4A010
ROM SHA-1: 757A4B9ED661DC6A6F33532AE64B0B063C79DBB3
ROM CRC32: 33B899C9
```

**Comment by infval** [comment]
The bug appeared in: https://github.com/TASVideos/fceux/commit/6145fe22ab8f6eebc71c5e84b14ed5d4ea87b302 (src/boards/bandai.cpp).
Before:
https://github.com/TASVideos/fceux/blob/0307e3b827da185054e3251bb4165734b890cf59/src/boards/bandai.cpp#L220
Now:
https://github.com/TASVideos/fceux/blob/129fbe3c323c56e8224f97afb0fe408df037b760/src/boards/bandai.cpp#L306
Submapper # 4 responds in the CPU $6000-$7FFF address range (https://wiki.nesdev.com/w/index.php?title=INES_Mapper_016). The game works after the fix, but I'm not sure it won't screw something else up.

**Comment by negativeExponent** [comment]
the same issue with mapper 16

https://github.com/TASEmulators/fceux/issues/458

**Comment by g0me3** [comment]
fixed as well with latest commits

**Comment by Chipsum** [comment]
Fixed
