### ISSUE TITLE
Hex Editor Issue

### ISSUE THREAD

**Issue by YingHuoChong4913** [TASEmulators/fceux#394]
When I use Hex Editor to copy continuous data, pasting is fine, but why can I only undo one by one? I hope the development team will be aware of this problem, otherwise it is really difficult to use in debugging.
This problem has been the case since version 2.3, and I hope it can be fixed.

**Comment by mjbudd77** [comment]
Which front end are you using? Qt or Win32?

**Comment by YingHuoChong4913** [comment]
Win 32 Yes.

**Comment by YingHuoChong4913** [comment]
No matter I use the Ctrl+Z shortcut or click Undo, I can only undo one by one.

**Comment by mjbudd77** [comment]
Can you try this on the Qt windows frontend and see if it has the same problem?

**Comment by YingHuoChong4913** [comment]
But I still think that the Win32 version is still the version used by many people. If this problem occurs, do you have to consider fixing it?

**Comment by YingHuoChong4913** [comment]
This problem still exists in the Qt Windows version, which is exactly the same as the one I mentioned.

**Comment by YingHuoChong4913** [comment]
Please you repair this Problem.

**Comment by mjbudd77** [comment]
I only work on the Qt front end. But I will fix the Qt

**Comment by YingHuoChong4913** [comment]
Thanks. But Win32 version, Who can Fixed This Quesion?

**Comment by mjbudd77** [comment]
This is fixed in the Qt GUI as of commit 8d4e535.

**Comment by zeromus** [comment]
@YingHuoChong4913 can you please clarify that it is only the case of PASTING where you expect it to be undone as one group? @mjbudd77  is that how you did it in your commit?

**Comment by mjbudd77** [comment]
@zeromus , yes Qt GUI saves the paste as a continuous multibyte patch and undoes the whole block as one action.
