### ISSUE TITLE
FCEUX wipes save data for MMC5+SRAM games on launch/boot

### ISSUE THREAD

**Issue by ShadowOne333** [TASEmulators/fceux#399]
I am currently working on a revised version hack of Zelda for NES, called Zelda Redux, and one of the features is a conversion of the game to the MMC5 mapper.

However, starting on version 2.3.0 of FCEUX, the MMC5 version is no longer maintaining the saves upon reboot or relaunch of FCEUX, or when reopening the ROM itself.
If I save and reset the game, the saves are visible and load fine, it's just on reboot/relaunch/restart that the saves are wiped. 

I also have an MMC1 version of the hack, and the MMC1 version plays and saves fine.

So far, three games have been tested:

1. Zelda Redux
2. Legend of Link: http://www.romhacking.net/forum/index.php?topic=29403.msg418910#msg418910
3. Super Mario All-Stars (NES):
http://www.romhacking.net/forum/index.php?topic=29403.msg418910#msg418930

All three of those games have been confirmed to have the exact issue at hand.
Lastly, a user on that thread specified that indeed the issue begun on FCEUX 2.3.0, while 2.2.3 did work fine with MMC5+SRAM games.

**Comment by epman100** [comment]
> 
> 
> I am currently working on a revised version hack of Zelda for NES, called Zelda Redux, and one of the features is a conversion of the game to the MMC5 mapper.
> 
> However, starting on version 2.3.0 of FCEUX, the MMC5 version is no longer maintaining the saves upon reboot or relaunch of FCEUX, or when reopening the ROM itself.
> If I save and reset the game, the saves are visible and load fine, it's just on reboot/relaunch/restart that the saves are wiped.
> 
> I also have an MMC1 version of the hack, and the MMC1 version plays and saves fine.
> 
> So far, three games have been tested:
> 
>     1. Zelda Redux
> 
>     2. Legend of Link: http://www.romhacking.net/forum/index.php?topic=29403.msg418910#msg418910
> 
>     3. Super Mario All-Stars (NES):
>        http://www.romhacking.net/forum/index.php?topic=29403.msg418910#msg418930
> 
> 
> All three of those games have been confirmed to have the exact issue at hand.
> Lastly, a user on that thread specified that indeed the issue begun on FCEUX 2.3.0, while 2.2.3 did work fine with MMC5+SRAM games.

hello ShadowOne333.

that person on that thread also mentioned the MMC5 SRAM problem also occurs on [puNES emulator](https://github.com/punesemu/puNES) where the saves do not work correctly.  can you also bring this problem up to the maker of puNES and have it fixed there as well?  thanks.

**Comment by mjbudd77** [comment]
The merge request has been merged. Is this issue now resolved?

**Comment by ShadowOne333** [comment]
> The merge request has been merged. Is this issue now resolved?

Been testing FCEUX with the commit merged, and so far all MMC5 games with SRAM I have tried have worked.
Feel free to close the issue if there's nothing more needed on our end.

**Comment by epman100** [comment]
unfortunately this specific fix seems to cause an unrelated problem where DarkDaiz's old Mario Adventure (SMB3) hack to display glitched graphics when running that in FCEUX, which did not occur in previous FCEUX dev builds

to fix that, use this RH (real hardware fix) patch for the Mario Adventure game:
[http://www.romhacking.net/hacks/6275/](http://www.romhacking.net/hacks/6275/)
