### ISSUE TITLE
Key-combos with CTRL, SHIFT, ALT not registering

### ISSUE THREAD

**Issue by WelfzTwingoFurs** [TASEmulators/fceux#402]
I noticed this when trying to play Secret Scout, where you need to hold Select and press a direction to move your inventory cursor. My select is bound to the Right-Shift but it wasn't working, so I put the input-display on screen and I noticed that when I had it pressed, the other keys I was pressing (WASD) would disable. CTRL and ALT would also disable them, even without having anything bound to them.

I downloaded version 2.3.0 to see if it was an issue with my keyboard, but these key-combos work fine in that version

**Comment by ClusterM** [comment]
Which build are you tried?

**Comment by ClusterM** [comment]
Seems like it's fixed.
