### ISSUE TITLE
How to edit tas in mac version of fceux

### ISSUE THREAD

**Issue by 368573607** [TASEmulators/fceux#408]
I know I cannot edit tas in the mac version of fceux. I want to know if there are any alternatives. Thanks🙏.

**Comment by 368573607** [comment]
When is it expected to be completed in 2022?

**Comment by mjbudd77** [comment]
The TAS editor has been ported to the Qt version and is now in testing phase. You can try it out on the latest dev build.

**Comment by meshuggahtas** [comment]
I believe this issue can be closed. The ability to use TAS Editor can be done in the Qt macOS version. Note it has some issues because of work in progress.
