### ISSUE TITLE
No help text

### ISSUE THREAD

**Issue by jeffythedragonslayer** [TASEmulators/fceux#415]
![image](https://user-images.githubusercontent.com/13253146/138634607-f6875ea9-d36c-4030-9a15-b24db3afcab7.png)

**Comment by meshuggahtas** [comment]
I had the same issue and the solution worked for me. Windows 10 x64 and both FCEUX and Qt FCEUX 2.5.0. That's a bummer that reading the local manual requires a kinda elaborate steps to unlock it.

I wanted to make a .chm issue that is the Qt macOS and Ubuntu can't open .chm files on default therefore there is no help text. So I'm going to write it here: is there any possibility to convert the .chm files into a cross platform friendly format? 

My sole suggestion would be packing (delivering an offline version of) the online web based manual so the user can use their browser to browse it. You can search, bookmark, printing and I guess I that's all the features the .chm offered.

**Comment by zeromus** [comment]
This also requires internet explorer to be installed and unbroken. 
To get offline docs, follow this link to download an FCEUX source snapshot
https://github.com/TASEmulators/fceux/archive/refs/heads/master.zip
then browse into the "web" directory, and you can probably figure it out from there.
