### ISSUE TITLE
[Win32] TAS Editor Crash

### ISSUE THREAD

**Issue by YuzuMSX** [TASEmulators/fceux#418]
I'm submitting the issue right now.

I'm using FCEUX 2.5.0 but lacks the TAS Editor.  (Causes a crash when clicking the TAS Editor on Tools tab)

- Windows 7 x64
- Intel Celeron 1.80Ghz
- RAM: 2GB

**Comment by vadosnaprimer** [comment]
Works for me.

**Comment by meshuggahtas** [comment]
The title says Win32 and the details says Windows 7 x64. Which one is it?

Windows 10 x64 FCEUX 2.5.0 (and Qt FCEUX 2.5.0) works for me.

**Comment by mjbudd77** [comment]
I’m wondering if the system mentioned above lacks the proper resources. 2GB memory is pretty small. How much of that memory is actually available for the application to use?

**Comment by meshuggahtas** [comment]
I've tried Ubuntu 20.04 + 1GB memory and I've could launch Qt FCEUX 2.5.0 + ROM open + Turbo (3fps but that's not the point) +  TAS Editor + PPU Viewer + Hex Editor + Debugger. I only got a crash after exiting from fceux, because of not enough memory.

Windows 10 x64 + 2GB under testing

**Comment by vadosnaprimer** [comment]
Couldn't reproduce.
