### ISSUE TITLE
The option --no-gui has no effect

### ISSUE THREAD

**Issue by fcharras** [TASEmulators/fceux#419]
Starting fceux with the command `fceux --no-gui` seemingly starts a normal instance of fceux with a gui.

The manual states "Enable or disable the GTK GUI." but isn't the gui implemented with qt ?

It would be nice having this option work, to be able to start a compute script in the background on a X-less host, without having to run a Xvfb server.

**Comment by mjbudd77** [comment]
The Qt GUI is required. The documentation needs to be updated. The GTK GUI and the —no-gui option are no longer supported.

**Comment by muzzol** [comment]
is there a way to hide option bar on linux?

I use it from attract mode and I can use --fullscreen but menus are visible.

I've tried with --noframe but is not working.

**Comment by mjbudd77** [comment]
There was an option to auto hide the main menu when going to full screen. You can find it in the config menu. It exists for versions 2.6.1 and later.

**Comment by zeromus** [comment]
so what's the action item here? which docs need to be updated?

**Comment by zeromus** [comment]
solved by some recent commit
