### ISSUE TITLE
PLEASE SUPPORT PS3 WITH TURBO KEYS

### ISSUE THREAD

**Issue by SecretTrueLight** [TASEmulators/fceux#421]
I think that Fceu is the best NES emulator on PS3.
It works stable, with smooth picture, without divining lines on screen.
But it really lacks turbo buttons in controller settings.
Please support PS3 with this feachure, at least for the final time.
But it would be perfect if you add online features someday.

**Comment by LukeSaward1** [comment]
This repository does not cover unofficial ports.
This is for desktop ports, not console ports.
