### ISSUE TITLE
Can't load rom more than once with Lua script

### ISSUE THREAD

**Issue by tag-u-r-it** [TASEmulators/fceux#422]
As the title suggests, Lua script will crash the emulator if the rom will get loaded after emu.frameadvance(?). Loading the rom works once but not twice if there is any delay between rom loads.

This script will crash the emulator unless you run it without the for loop:
```
while (true) do
	emu.loadrom("path/to/rom")
	for i = 600, 0, -1 do
		emu.frameadvance();
	end
end
```
out:
`542461 segmentation fault (core dumped)`

Did I stumble on an actual bug or is there something I need to know about Fceux?

Version 2.4.0, installed from the AUR repository.

I also downloaded the latest git version, built it and it didn't resolve the issue either.

**Comment by tag-u-r-it** [comment]
Were you able to reproduce the issue? Or was there something wrong with my script?

**Comment by mjbudd77** [comment]
I think your script is fine. I did find a threading issue with the load rom function in the SDL port. I’ve made some changes to make it better. But I will experiment to get it better.
