### ISSUE TITLE
[SDL] What are mpeg4.conf and ac3.conf about?

### ISSUE THREAD

**Issue by TCH69** [TASEmulators/fceux#423]
So, I didn't noticed those files until yesterday when I started recording with the emulator started from my terminal and these popped up.
`Error: Failed to open file '/usr/home/fa2_l/.fceux/avi/mpeg4.conf' for reading
AVI Encoded Video FPS: 60.099000000000
CODEC Supports PIX_FMT:0
Error: Failed to open file '/usr/home/fa2_l/.fceux/avi/ac3.conf' for reading
Output #0, avi, to '/usr/home/fa2_l/Records/smb1.avi':
  Stream #0:0: Video: mpeg4, yuv420p, 256x240, q=2-31, 400 kb/s, 60.10 tbn
  Stream #0:1: Audio: ac3, 48000 Hz, mono, fltp, 64 kb/s`
It looks like `mpeg4.conf` is the video recording configuration file, which may have answered my question about why all of my records are all in very bad quality (256x240, maybe because the file was not edited). But somehow those files are not listed anywhere.
So, what (exactly) are those files for and how should I configure it?

**Comment by mjbudd77** [comment]
Those files are to save encoder settings for avi recording when using the ffmpeg backend. You should never edit those by hand, if you want to increase quality, I recommend changing your video prescaler to prescale 2x in video config window. Also, I recommend changing your encoders. Use libx264 for video and libmp3lame for audio.

**Comment by mjbudd77** [comment]
I will also go on to say that only differences from default settings are saved in those files.

**Comment by TCH69** [comment]
Thank you about that, but it seems to me that changing the prescaler only upscale the video output and it doesn't really change the video quality at all. I'm recompiling the emulator with x264 now and I'll be back as soon as possible.

**Comment by mjbudd77** [comment]
The SDL port records the avi with the same settings as the video viewport. If you have ffmpeg libraries already precompiled, libx264 should already be available.

**Comment by TCH69** [comment]
I've just done compiling all of them now and it's working good now, thanks!
