### ISSUE TITLE
Linux build fails to compile

### ISSUE THREAD

**Issue by Blad3forc3** [TASEmulators/fceux#425]
Hello,

I am getting this error during compilation at 100%

[100%] Linking CXX executable fceux
/usr/bin/ld: CMakeFiles/fceux.dir/lua-engine.cpp.o: in function `savestate_create_aliased(lua_State*, bool)':
lua-engine.cpp:(.text+0x6617): warning: the use of `tempnam' is dangerous, better use `mkstemp'
/usr/bin/ld: CMakeFiles/fceux.dir/drivers/Qt/AviRecord.cpp.o: in function `X264::init(int, int)':
AviRecord.cpp:(.text+0x251): undefined reference to `x264_encoder_open_163'
/usr/bin/ld: CMakeFiles/fceux.dir/drivers/Qt/AviRecord.cpp.o: in function `X265::init(int, int)':
AviRecord.cpp:(.text+0x595): undefined reference to `x265_encoder_open_200'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/fceux.dir/build.make:5055: src/fceux] Error 1
make[1]: *** [CMakeFiles/Makefile2:99: src/CMakeFiles/fceux.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by mjbudd77** [comment]
Which linux distro are you using and what versions of x264 and x265 do you have installed?

**Comment by Blad3forc3** [comment]
kde neon. 

x265 [info]: HEVC encoder version 3.5+10-82786fccc
x265 [info]: build info [Linux][GCC 9.3.0][64 bit] 8bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2

x264 0.163.3059 b684ebe
(libswscale 6.0.100)
built on May 29 2021, gcc: 9.3.0
x264 configuration: --chroma-format=all
libx264 configuration: --chroma-format=all
x264 license: GPL version 2 or later

**Comment by mjbudd77** [comment]
This build error doesn’t make sense. It seems like you have mismatched development header files and runtime libraries. Please double check that the versions of the development header packages match the runtime library packages for libx264 and libx265. Kde neon is based on Ubuntu and I know Ubuntu 20.04 builds fine (since that is what I use)

**Comment by Blad3forc3** [comment]
I did compile ffmpeg from source to support hdr in handbrake and x265 was enabled could this have mismatched the files?

**Comment by mjbudd77** [comment]
Yes, if ffmpeg libraries are built using a different version then this could be a problem. Why did you choose to build from source over using stable packages from the package manager

**Comment by Blad3forc3** [comment]
the ffmpeg version didnt support hdr which the git build of handbrake did

**Comment by mjbudd77** [comment]
Either way. This is not an issue that can be fixed on my end. The function names in your error output are not directly called the in code, which means that they were altered by the C preprocessor prior to compilation. This can only happen by the included header files that are external to the project and therefore not within my control. I recommend uninstalling ffmpeg, libx264,and libx265 source and build against the development packages supported by your distribution

**Comment by mjbudd77** [comment]
Issue is due to external environment. Closing.
