### ISSUE TITLE
Enter multiple game genie codes into Add/Edit code for the rom emulator

### ISSUE THREAD

**Issue by DROCK1981** [TASEmulators/fceux#426]
I am needing to enter a game genie code for a rom. The code cotains two 8 character letters to make one entry for the desired code effect. The fceux emulator will only allow me to enter one code where two are required. The two codes are separated by a + symbol. Is there a certain way the two codes need to be entered to make one? The example looks like this:
xxxxxxxx + xxxxxxxx 
![Screenshot_20211128-011444_NESemu](https://user-images.githubusercontent.com/95161274/143733357-f5cce69d-6e73-497d-aafc-13bd5b211156.jpg)
![Screenshot_20211128-011435_NESemu](https://user-images.githubusercontent.com/95161274/143733359-56eb0c75-eb59-454c-9163-ef984db70b86.jpg)

I hope maybe there is a resolution to this issue please reply when possible to my email address 
d3erock@protonmail.com

Thank you.

**Comment by mjbudd77** [comment]
I don’t recognize this menu? What version of fceux is this? What operating system are you running on?

**Comment by Yave-Yu** [comment]
You would go to emu-ex-plus-alpha, this emu uses FCEUX core though.
