### ISSUE TITLE
512-color palette doesn't affect AVI output

### ISSUE THREAD

**Issue by Yave-Yu** [TASEmulators/fceux#429]
I used an 8-same-color palette as 512-color palette so any emphasises will "disappear".
Unfortunately, outputed AVI doesn't have 512-color palette, it just like regular 64-color and internal emphasis coloring.

**Comment by mjbudd77** [comment]
Please specify what port (win32 or Qt) and version of fceux you are using when creating issue reports. It would also be nice to have steps to reproduce your issue.

**Comment by Yave-Yu** [comment]
Win32, 2.5.0 stable.
[NoMask.zip](https://github.com/TASEmulators/fceux/files/7690412/NoMask.zip)
First load this palette, then open a game which uses color emphasis such as James Bond Jr., with this palette, you won't see any emphasis effect.
Now output an AVI, when finish, play it and you will see emphasis still remains, not like emulator itself.

**Comment by mjbudd77** [comment]
Can you try this on the Qt/SDL win64 version 2.5.0 and tell me if it has same issue? The Qt port records the video data a little differently.

**Comment by Yave-Yu** [comment]
Yeh, I tried Qt FCEUX 2.5.0, it doesn't even affect 512-color palette in main screen, just like regular 64-color...and I tried to record AVI, then stuck a little and FCEUX has stopped working...
