### ISSUE TITLE
[question] On fceux for nes how to hide the tas window?

### ISSUE THREAD

**Issue by SIREN87** [TASEmulators/fceux#431]
https://ibb.co/rxp29MT

Im using fceux 2.3.0 for nes and my son pressed something or other. Now when i minimize the tas editor it stays on top. Any idea how to hide it?

Also is there an fceux for snes games? If yes can someone post a link or give a name for it?

**Comment by meshuggahtas** [comment]
- The link doesn't works.
- If you minimize, it should go to the bottom left corner. If you want to fully hide it, you need to close it.
- FCEUX only runs NES games. Try BizHawk @ https://github.com/TASEmulators/BizHawk
