### ISSUE TITLE
Dragging window to second monitor stops graphics updates 2.5.0 Non-QT

### ISSUE THREAD

**Issue by ghost** [TASEmulators/fceux#432]
**Describe the bug**
When moving an FCEUX 2.5.0 window to second monitor, graphics stop updating entirely. Bringing the window back to the original monitor resumes graphics updates. 

**Potentially relevant**
I have unbalanced displays (4k on one, 1080p on other). 
This was using the Win32 binary on an x64 Windows 10 machine. But I also checked it in the current Non-QT x64 interim binary, same deal as the Win32 binary.
This issue doesn't seem to be present in the Qt build.

**To Reproduce**
1. Open a rom in FCEUX 2.5.0 (same whether opening FCEUX or opening a .nes associated with FCEUX)
2. Check gameplay is working. Take note of player sprite's visual position or SMB1 timer, something that visually changes.
3. Click and drag window to second monitor and drop it there
4. Use controller to move player or something. For me, no graphics update.
5. Click and drag window back to the original monitor and drop it there. Graphics now update again.
6. Look at player sprite's visual position. 

For me, it looks like the emulation continued while the window was on the second monitor (player position responded to input, music continued, timer decreased, death by goomba processed) but FCEUX didn't visually update while over there, only when back to the original monitor it was opened on.

**Expected behavior**
I would expect graphics updates to stop while dragging the FCEUX window, but not once the window has been dropped onto the second monitor.

**Evidence**
I recorded a 47 second video of this happening with OBS: https://www.youtube.com/watch?v=fi-H_j9-XAA **[Attached as .mp4]**
Unfortunately it's too hard for me to drag windows around in a GIF's length of time, and screenshots don't evidence the issue.

**Versions**
 - OS and Version: Windows 10 (Build 19043) x64 i7
 - Version of FCEUX: Non-QT, FCEUX 2.5.0 msvc 1928 x86 release 02:39:35 Oct 22 2021
 - (Also present in non-QT FCEUX 2.5.0-interim msvc 1916 x64 release 02:41:40 Dec 14 2021)

**Additional context**
This happened both with SMB1 and with my own homebrew code. Can't test other commercial roms as I don't have any other carts to rip.
While the window is on the second monitor, it won't update the graphics even if I reset, load recent or load a fresh rom. Since Windows automatically opens FCEUX on the primary monitor, there is no way to move it to the other, impacting workflow. Qt build looks functional enough so I guess I'm switching to that, just wanted to report this issue anyway

https://user-images.githubusercontent.com/96143007/146080015-14b06c53-3368-4fa7-bb3c-8c8475dd5a71.MP4

.

**Comment by meshuggahtas** [comment]
- Go to **Config > Video Configuration**
- **Windowed Settings** (2nd tab group) **DirectDraw** dropdown menu
- Change from No hardware acceleration to any of the other 2
