### ISSUE TITLE
qt taseditor

### ISSUE THREAD

**Issue by vadosnaprimer** [TASEmulators/fceux#433]
- [x] None of the settings get saved across sessions (aside from font). ** All should be saved now.

- [x] If you hover above scrollbar and scroll the mouse wheel, scroll direction will still be reversed. Clicking on scrollbar above the slider is meant to scroll 1 screen to that direction, but it scrolls to the opposite. Also scroll interval is different for a single notch, it should be 6 for both.

- [x] When changing piano roll font, the second column doesn't have enough space unless I use Courier.

- [x] Font in bookmarks and branches should also be bold.

- [x]  Closing taseditor and picking Cancel in the Save dialog results in it still closing without anything saved, and then taseditor can't be opened again until I restart fceux.

- [x] Follow Cursor is ignored when you rewind using Wheel+RMB.

- [x] Holding < or > button on the Playback panel should work the same as holding the frame advance hotkey: step once, then after a bit run (advance or rewind).

- [x] #F0F0F0 would be a better color for listview border, less distracting.  ** NOTE ** Made grid color configurable.

- [x] Default font should be sans serif, also less distracting. ** NOTE ** I'm sticking with the same monospace default text as other parts of the GUI. The courier matching logic is cross platform so I'm going to leave this for stability purposes. 

- [x] History view doesn't get updated after you've used Recording mode.

- [x] Clicking on the same cell repeatedly to set and unset input has HUGE delay. About half a second until your new click actually works. ** Double click logic was being triggered. Added logic to double click as necessary.

- [x] Holding Alt allows drawing across columns.

- [x] Double-clicking on existing marker should allow dragging it to another row. In win32 taseditor you can also throw it outside the dialog to remove it. ** NOTE ** Implemented marker drag n drop.

- [x] The right panel is too huge IMO. If elements are grouped closer like in win32 taseditor it won't occupy so much space overall. Using 4-score is basically impossible on my 1440 wide monitor. ** NOTE ** the right panel is resizeable and the piano roll font size can be reduced to fit all on one screen.

- [x] Frame column has way too many digits. Back when AnS was designing taseditor 2.0, we calculated that maxing out the counter used in win32 version will result in 46 hours of gameplay, which nobody ever does on NES in one sitting. Maxing out the qt version counter is 46296 hours, or 1929 days.

**Comment by meshuggahtas** [comment]
Auto restore last position doesn't fixes the ending position. Incosistently increases the ending position.

TODO: add gif for visual example

**Comment by vadosnaprimer** [comment]
Hovering above scrollbar still has different scroll using than above pianoroll. Should be 6 for both.

Best font options I have available are Cascadia Code and Mono, but if I use them, frame column is still too narrow for the text to properly fit in.

![изображение](https://user-images.githubusercontent.com/7092625/147760244-942cae9d-7906-46e2-bd11-05462a20cebf.png)

Setting grid color only sets it for rows, not columns?

![изображение](https://user-images.githubusercontent.com/7092625/147760514-a766fbb9-ca3a-4daa-9b8a-697a7111f011.png)

**Comment by vadosnaprimer** [comment]
If I disable the second controller, inputroll still has space for it, causing horizontal scrollbar to appear,

It would be better to disable automatic resizing of the right panel.

Font in Branches view should also be centered inside the cards.

If you disable Follow Cursor and unpause emulation, you won't be able to keep frame 0 visible: the view will scroll to frame 1, 2, or 3 all the time.

When going through emulated frames down using RMB+Wheel, the view should keep scrolling following the cursor. Right now if you scroll fast, the view wraps around putting cursor at the top, then stays stationary while the cursor is moving down, then if you're quick it wraps around again. This doesn't happen when navigating up, which is correct.

It would probably be better to ignore grid color changes when drawing table header, because the color that makes input area look good, makes the header border disappear.

![изображение](https://user-images.githubusercontent.com/7092625/147850760-d156f5a4-dc61-4ded-b3eb-d101cc93efbe.png)

There should be no delay in how quickly the hover screenshot changes when you move to _another_ branch. Delay (if it's already there) should only affect how fast alpha fades down when you move away entirely.

Greenzone Saving Options don't seem to do anything (Project file saving options menu).

Pointing to an existing file when saving should show a warning that the file exists.

**Comment by vadosnaprimer** [comment]
I created several branches at the same frame, from the same root, and the tree view looks like this

![изображение](https://user-images.githubusercontent.com/7092625/148799891-24afb60e-c957-4a94-b39d-90fead339e8d.png)

**Comment by mjbudd77** [comment]
I changed the vertical positioning logic for the branch tree. This should be better as of commit 26386b84838201063d6e0bbb7392b214a63062fb.

**Comment by vadosnaprimer** [comment]
LGTM!
