### ISSUE TITLE
macOS EXC_BAD_ACCESS sometimes after quitting FCEUX

### ISSUE THREAD

**Issue by meshuggahtas** [TASEmulators/fceux#435]
**Describe the bug**
Sometimes after quitting FCEUX, a problem report comes up on macOS about unexpected quit.

**To Reproduce**
There is no known consistent reproduction of this issue. But it should appear 1 out of 3 from the following steps:
1. Open FCEUX
2. Open a ROM
3. Press X to close FCEUX

**Expected behavior**
No unexpected "crash" after quitting the program

**Screenshots**
Non relevant

**(please complete the following information):**
 - OS and Version: macOS Big Sur 11.0 **edit: virtualized, might be relevant to this issue**
 - Version of FCEUX used (QT or non-QT): FCEUX Qt 2.5.0

**Additional context**
- My log from macOS crash: https://pastebin.com/04KZrEMK
- edit: Pressing reopen on the dialog won't reopen FCEUX. Sometimes it does reopen.

**Comment by mjbudd77** [comment]
I believe this is now fixed. See recent commit b05e210982e378799cae9d724394f9cb2c87e22d

**Comment by meshuggahtas** [comment]
OK, fixed, closing issue
