### ISSUE TITLE
Qt Screenshot no message

### ISSUE THREAD

**Issue by meshuggahtas** [TASEmulators/fceux#436]
**Describe the bug**
There is no message (on HUD and in message log) after taking a snapshot/screenshot (F12)

**To Reproduce**
1. Open FCEUX
2. Open ROM
3. F12

**Expected behavior**
Message is shown

**Screenshots**
![fceuxscreenshot](https://user-images.githubusercontent.com/31288337/147075897-4b73d514-1f0b-4927-9319-8b371887338e.PNG)

**(please complete the following information):**
 - OS and Version: Windows 10 x64 and macOS Big Sur 11.0
 - Version of FCEUX used (QT or non-QT): Qt FCEUX 2.5.0 x64 and macOS

**Additional context**
No

**Comment by mjbudd77** [comment]
Fixed in commit 4006bb5

**Comment by meshuggahtas** [comment]
OK, fixed, retested on the two platform. Closing issue.
