### ISSUE TITLE
macOS Menu hotkeys don't work

### ISSUE THREAD

**Issue by meshuggahtas** [TASEmulators/fceux#438]
**Describe the bug**
Unable to use menu hotkeys like Alt+F or other variants. Tried to press all modifier keys.

**To Reproduce**
Try to use hotkey to press a menu element. For example Alt+F. I believe it should be Ctrl or CMD but doesn't works.

**Expected behavior**
Able to use menu hotkeys.

**Screenshots**
No

**(please complete the following information):**
 - OS and Version: macOS Big Sur 11.0
 - Version of FCEUX used (QT or non-QT): Qt FCEUX 2.5.0

**Additional context**
Windows 10 x64 Qt FCEUX 2.5.0 works

**Comment by mjbudd77** [comment]
I've looked into this before and everything I've read tells me this is a Qt5 limitation on the macOS. If you have seen different, please direct me to where I can read on how to fix it.

**Comment by meshuggahtas** [comment]
The Qt FCEUX says Qt version 5.15.2. This page doesn't explicitly says menus don't work. It has different solutions for different problems. Since I have no idea what is the technical background of this project to help thinking in it, I will just link the page:
https://doc.qt.io/qt-5/macos-issues.html#menu-bar

**Comment by meshuggahtas** [comment]
For context, here is Safari's native menu:
![safari_native_menu](https://user-images.githubusercontent.com/31288337/147389771-ee87c77d-6ae8-4da0-9853-e5b45bbbf86e.png)

And here is currenlty FCEUX's native menu:
![fceux_native_menu](https://user-images.githubusercontent.com/31288337/147389775-2e44f78d-41c6-46a9-b329-7b3537b7d1dd.png)

**Comment by mjbudd77** [comment]
In the GUI options config window, you can choose to use the native OS menu bar. Then the menu will appear like you have it with safari.

**Comment by meshuggahtas** [comment]
Nice! They work after restarting FCEUX. The hotkeys also works. The original native menu list I show in the screenshot also stays. 

There is a little bit of difference between the original context menu and this native one:
- About FCEUX and About Qt is at main FCEUX
- File > Quit is now at main FCEUX

Not really an issue, just surprised by the difference.

Added screenshot for FCEUX native menu
![fceuxrealnative](https://user-images.githubusercontent.com/31288337/147390131-a3b00e70-76f1-4a5c-b63e-30857f941f9f.png)


I think this should be the default setting for the macOS distribution.

**Comment by mjbudd77** [comment]
I get inconsistent behavior when using the macOS system menu bar. Until I can see consistency, I will not be making this the default setting.

**Comment by mjbudd77** [comment]
I finally figured out how to fix the menu accelerator keys in mac OSX. Fixed in commit c0dff9b.

**Comment by mjbudd77** [comment]
Closing bug as the resolution is about as good as it’s going to get.

**Comment by meshuggahtas** [comment]
It's okay to close this issue.

I'm going to try some stuffs in MacOS tomorrow, with testing this issue first.

I see the fix wasn't simple, but let me ask something and show something:
- Qt officially supported MacOSes: macOS 10.13, macOS 10.14, macOS 10.15, macOS 11
 (<-- I've tested on 11 Big Sur). Which version did you use where menu handling (hotkeys drawn and functioning) was inconsistent?
- Regarding "menu accelerator keys do not appear to work when using the native Mac OS menu bar", the bottom of https://doc.qt.io/qt-5/macos-issues.html#limitations it says:
Actions in a [QMenu](https://doc.qt.io/qt-5/qmenu.html) with accelerators that have more than one keystroke ([QKeySequence](https://doc.qt.io/qt-5/qkeysequence.html)) will not display correctly, when the [QMenu](https://doc.qt.io/qt-5/qmenu.html) is translated into a Mac native menu bar. The first key will be displayed. However, the shortcut will still be activated as on all other platforms. <-- Sorry if your already checked it out
