### ISSUE TITLE
Qt message print to end of the last message

### ISSUE THREAD

**Issue by meshuggahtas** [TASEmulators/fceux#439]
**Describe the bug**
Sometimes a new log message in the Message log gets printed to the end of the last line instead of a new line.

**To Reproduce**
1. Open FCEUX
2. Open Message log
3. Open a ROM
4. Close ROM
5. Open a ROM

**Expected behavior**
After the NTSC set line, it should be a newline for the new messages.

**Screenshots**
edit: added
![Képkivágás](https://user-images.githubusercontent.com/31288337/147096101-772ac0db-5da6-49db-a86a-777f4bed7a34.PNG)

**(please complete the following information):**
 - OS and Version: macOS Big Sur 11.0
 - Version of FCEUX used (QT or non-QT): Qt FCEUX 2.5.0

**Additional context**
Also affects Windows 10 x64

**Comment by mjbudd77** [comment]
Fixed in commit 79d989a7987558950c8e9425b528f7451f5eb521

**Comment by meshuggahtas** [comment]
OK, fixed, retested on the two platforms. Closing issue.
