### ISSUE TITLE
Ubuntu can't install

### ISSUE THREAD

**Issue by meshuggahtas** [TASEmulators/fceux#441]
**Describe the bug**
Unable to install.

**To Reproduce**
Try installing.

**Expected behavior**
I can install.

**Screenshots**
No

**(please complete the following information):**
 - OS and Version: Ubuntu 20.04 (virtualized with VirtualBox, should be irrelevant to the issue, as I don't encountered this issue before with other applications)
 - Version of FCEUX used (QT or non-QT): QT Fceux 2.5.0

**Additional context**
Failed to install file: not supported. I have a 64bit Intel Core i5-6400 CPU. I've thought this shouldn't be a problem.

**Comment by meshuggahtas** [comment]
On Ubuntu 20.04 default settings, if I click on a link on this github repo release links or the artifact, I can either open it with Software Installer or save it. The above comment shows the "Open with Software Installer" one.

If I save the .deb file and click Open With Software Install, I could install it without an issue...

I'm unsure about who is at false here. I didn't encounted this issue with other applications. Hmm...

**Comment by mjbudd77** [comment]
If the application installed fine after fully downloading it, I fail to see how this is my issue.

**Comment by meshuggahtas** [comment]
Yes sorry, when I first wrote the issue, only the first option of the two download possibility yielded in error in Ubuntu Software.

I will try with other .deb files and browsers to investigate the issue.

**Comment by meshuggahtas** [comment]
I have retested with other .deb files, some of them worked (Default browser is Firefox and you can either download and run using Software Installer or Open Archive) and some of them didn't worked. My conclusion is this is not a project problem but something with my Virtualbox environment perhaps.

Another example .deb that shows **Failed to install file: not supported:** Atom 1.58.0

Closing this issue because the issue seems out of scope of the project.
