### ISSUE TITLE
Ubuntu native OS menu not working

### ISSUE THREAD

**Issue by meshuggahtas** [TASEmulators/fceux#442]
**Describe the bug**
Ability to use native menu

**To Reproduce**
Options > GUI Config > Use Native OS Menu Bar

**Expected behavior**
I can use native menu

**Screenshots**
![VirtualBox_Ubuntu oli_25_12_2021_18_39_54](https://user-images.githubusercontent.com/31288337/147390528-12badfd5-a197-4b76-9ca0-ca1f78dca9e2.png)

**(please complete the following information):**
 - OS and Version: Ubuntu 20.04 (Virtualized, probably doesn't matter)
 - Version of FCEUX used (QT or non-QT): QT FCEUX 2.5.0

**Additional context**
No

**Comment by mjbudd77** [comment]
I believe that there is more configuration that must be done to the gnome desktop environment to make this work. The Qt documentation is pretty clear that this is not guaranteed to work on every OS / window environment.

**Comment by mjbudd77** [comment]
I'm not sure standard Ubuntu supports this. My research tells me that only certain linux variants support this behavior, like Ubuntu Unity. There is nothing on my end that I can do any differently, I only set a flag in the Qt menu bar to attempt to use a system menu bar. Qt handles the rest. So if there is a bug, its in Qt, not in fceux.
