### ISSUE TITLE
can't bind to comma key

### ISSUE THREAD

**Issue by dmwit** [TASEmulators/fceux#443]
**Describe the bug**
If you change your input configuration to use the comma key for something, that works fine until fceux exits; when it restarts, the comma binding is gone, even if you saved it in the previous go.

**To Reproduce**
1. Options -> Input config -> Configure
2. Click 'Change' next tothe current active button mapping for A
3. Hit the comma key
4. Press Save
5. Exit fceux, and restart it
6. Options -> Input config -> Configure
7. There is no current active button mapping for A

**Expected behavior**
The comma key should behave like the A button.

**Additional context**
It seems pretty clear what's going wrong. In `~/.fceux/input/keyboard/default.txt` there is text like this:

    keyboard,default,config:0,a:k,,b:kB,<etc. etc.>,turboB:k

Probably the `k,,` is getting interpreted as an empty key binding followed by two comma separator, rather than a comma key binding and one separator. Some escaping in the code that creates and reads this file should clear things up.

**Comment by mjbudd77** [comment]
This should be fixed in the latest development commit. Keep in mind that there is a default hot key assigned to the comma key for input display video overlay. You will have to clear or set that hot key to a different key to ensure that the comma key can be used as a gamepad button.
