### ISSUE TITLE
Debugger bugs

### ISSUE THREAD

**Issue by SusiKette** [TASEmulators/fceux#444]
I have encountered few bugs in the debugger:

1. Breakpoints and address bookmarks are not saved
2. Symbolic debug naming dialog cannot be opened on zero page addresses. You can still get the symbolic name there if you go to the RAM area in the debugger and set it there, but it's a bit inconvenient to do that way. Also the symbolic name is displayed in a strange manner in indirect addressing modes. Current `LDA ($5A symbolic_name),Y @ $000D = #$00`, and what I think would look better ``LDA ($5A),Y symbolic_name @ $000D = #$00``

These were encountered on FCEUX mscv 1916 x64 release on Windows 10 x64

**Comment by mjbudd77** [comment]
This issue is on the Qt/SDL version?

**Comment by SusiKette** [comment]
How can I check that? I didn't see Qt or SDL mentioned in the 'About' window

**Comment by mjbudd77** [comment]
If the help menu doesn't have an "About Qt" item. Then you are not using the Qt/SDL version. I recommend giving the win64 Qt/SDL development build a try. The debugger has changed a bit in the Qt/SDL version. You might like it better.

**Comment by ClusterM** [comment]
> 2\. Current `LDA ($5A symbolic_name),Y @ $000D = #$00`, and what I think would look better `LDA ($5A),Y symbolic_name @ $000D = #$00`

Actually, these lines have two different meanings.
`LDA ($5A symbolic_name),Y @ $000D = #$00` means that `$5A` has name `symbolic_name`,
`LDA ($5A),Y symbolic_name @ $000D = #$00` means that `$0D` has name `symbolic_name`.

Line can contain both of them:

![image](https://user-images.githubusercontent.com/4236181/153206606-182cd812-9c64-4503-a18a-ad9eb6d3bfc8.png)

> Symbolic debug naming dialog cannot be opened on zero page addresses.

Seems like it can't be opened for zero-page addresses when the address already has some symbolic name. I'll check it.

**Comment by ClusterM** [comment]
I did some tests.

`05 01     ORA $01` - dialog cannot be opened
`15 02     ORA $02,X @ $0042` - dialog can be opened only if the address does not already have a name
`25 03     AND $03` - dialog cannot be opened
`35 04     AND $04,X @ $0044` - dialog can be opened only if the address does not already have a name
`45 05     EOR $05` - dialog cannot be opened
`55 06     EOR $06,X @ $0046` - dialog can be opened only if the address does not already have a name
`65 07     ADC $07` - dialog cannot be opened
`75 08     ADC $08,X @ $0048` - dialog can be opened only if the address does not already have a name
`85 09     STA $09` - dialog cannot be opened
`95 0A     STA $0A,X @ $004A` - dialog can be opened only if the address does not already have a name
`A5 0B     LDA $0B` - dialog cannot be opened
`B5 0C     LDA $0C,X @ $004C` - dialog can be opened only if the address does not already have a name
`C5 0D     CMP $0D` - dialog cannot be opened
`D5 0E     CMP $0E,X @ $004E` - dialog can be opened only if the address does not already have a name
`E5 0F     SBC $0F` - dialog cannot be opened
`F5 10     SBC $10,X @ $0050` - dialog can be opened only if the address does not already have a name
`06 11     ASL $11` - dialog cannot be opened
`16 12     ASL $12,X @ $0052` - dialog can be opened only if the address does not already have a name
`26 13     ROL $13` - dialog cannot be opened
`36 14     ROL $14,X @ $0054` - dialog can be opened only if the address does not already have a name
`46 15     LSR $15` - dialog cannot be opened
`56 16     LSR $16,X @ $0056` - dialog can be opened only if the address does not already have a name
`66 17     ROR $17` - dialog cannot be opened
`76 18     ROR $18,X @ $0058` - dialog can be opened only if the address does not already have a name
`86 19     STX $19` - dialog cannot be opened
`96 1A     STX $1A,Y @ $001A` - dialog can be opened only if the address does not already have a name
`A6 1B     LDX $1B` - dialog cannot be opened
`B6 1C     LDX $1C,Y @ $001C` - dialog can be opened only if the address does not already have a name
`C6 1D     DEC $1D` - dialog cannot be opened
`D6 1E     DEC $1E,X @ $005E` - dialog can be opened only if the address does not already have a name
`E6 1F     INC $1F` - dialog cannot be opened
`F6 20     INC $20,X @ $0060` - dialog can be opened only if the address does not already have a name

**Comment by ClusterM** [comment]
Dialog can't be opened when there is a space after a two-digit address

![image](https://user-images.githubusercontent.com/4236181/153218470-771d1927-bd17-45a0-b9fb-fdd506b04c59.png)

Because of this check: https://github.com/TASEmulators/fceux/blob/a75c27d517cf8a166e2968918a5846a6d80d84df/src/drivers/win/debugger.cpp#L1713

Need to improve address validation code.

**Comment by ClusterM** [comment]
Please try the latest dev build at commit https://github.com/TASEmulators/fceux/commit/132e062d777b193f5d6be4c992ae0bc8eaa84b4d.

**Comment by thor2016** [comment]
Over a year has passed since a resolution was committed. Closing due to apparent lack of interest on the bug creator side.
