### ISSUE TITLE
Zelda 1 object/BG priority in Dungeon doors

### ISSUE THREAD

**Issue by ShadowOne333** [TASEmulators/fceux#445]
**Bug:**
In Zelda 1 inside Dungeons, the door background tiles have priority over Link's sprite, covering Link when he goes through one of these doors. However, using the latest FCEUX (and with other version as well, at least since 2.3.1), walking through any up or down doors inside Dungeons with Link makes it so Link has priority over the door tiles.
Interestingly enough, this doesn't seem to be the case for Left or Right doors, as those ones do have the proper priority in these cases. It seems to only be the Up and Down doors which are affected.

**To Reproduce:**
1. Start a new game
2. Go to any kind of Dungeon (Dungeon 1 is easiest to access and easiest to test this)
2. Walk to any up/down door
3. Link's sprite is always shown on top of the door tiles

**Expected behavior:**
Link's sprite should be covered by the up/down door tiles when walking through them.
Proper behaviour can be visualized in the following video, around 7:01:
https://youtu.be/Lna7Zw1TnBE?t=420

**Screenshots:**
![Zelda-2](https://user-images.githubusercontent.com/13888698/148794033-43d3b9ee-d0ae-4057-afcc-15b021ba184c.png) ![Zelda-3](https://user-images.githubusercontent.com/13888698/148794038-26722d34-408f-4abf-bdb4-9017d32e7244.png)

 - OS and Version: 32bit Linux/Gentoo with FCEUX running through Wine (also tested in RetroArch's core on a Nintendo Switch and in a Windows 10 64bit machine)
 - Version of FCEUX used: 2.5.0

**Comment by mjbudd77** [comment]
I looked at this issue using the sprite viewer in the Qt version. For the left/right doorways, the BG priority bit is set on link’s sprite. For the up/down doorways that bit is not set. Not sure why the bit is not set for the up/down cases, but I believe that the bit should be set to get the desired behavior.

**Comment by zeromus** [comment]
can't repro myself on latest git in win32 build

**Comment by ShadowOne333** [comment]
I tested this on the most recent official release for win32 (2.6.1) and I can still reproduce it.
I can't test the latest git build as I have no way to compile a win32 build of it.

**Comment by mjbudd77** [comment]
There are automatic builds of the latest git every time a change is made. You can download the builds from the links in the readme.md file that can be accessed from the main code view of this repo right here on GitHub

**Comment by mjbudd77** [comment]
I believe I found the issue. This issue presents itself when the disable sprite limit config option is set to true (max sprites is 64 instead of normal 8). Unchecking this option in the video config dialog will fix the issue. I tested this in the Qt port and found that the default value in the Qt port was to have the option checked (sprite limit disabled). This disagrees with the default of the win32 port. I have now changed the Qt port to match the win32 port so that the sprite limit will always default to enabled (if no previous config settings exist).

**Comment by ShadowOne333** [comment]
Disabling the option under 'Video -> Emulation' called "Allow more than 8 sprites per scanline" does effectively seem to fix the priority issue with the tiles and Link's sprite.
Is there any specific reason as to why allowing more than 8 sprites just ignores the sprite priority for those instances?

**Comment by zeromus** [comment]
it's not sprite priority. games will pile up sprites in the top left corner to stop further sprites on the line from being rendered after the limit is reached. with no limit, this obscuration method doesn't work. emulators (for ALL platforms, for this reason) need to default to enforcing the sprite limit
