### ISSUE TITLE
RAM Search is displaying addresses from mirrors

### ISSUE THREAD

**Issue by SusiKette** [TASEmulators/fceux#446]
RAM Search is displaying addresses from mirrors of the $0000 - $07FF region.

1. Open RAM Search
2. Use aby "Compare To/By" mode except for "Specific Address" (I used "Specific Value")
3. Search until you have only a handful of results left
4. See that most of them are outside the RAM memory region

This wasn't an issue in any previous FCUEX version I've used. When searching I only expected to have $0086 as the final result, but I also had $0886, $1086 and $1886 in the list. If this is not a bug, then can you at least add some way to automatically filter the list based on what the user wants (or by what regions the game uses). For example, most games don't use the $6000 - $7FFF region but FCEUX has always displayed it for no reason for game that don't use it.

OS and FCEUX version:
 - Windows 10
 - FCEUX 2.6.0-interim git (Qt)

**Comment by mjbudd77** [comment]
I have made some changes that I believe will help. Please try the latest dev build at commit 1acdb31.

**Comment by mjbudd77** [comment]
@SusiKette , is the fix good?
