### ISSUE TITLE
Mapper 218 support for magic floor

### ISSUE THREAD

**Issue by kotenok2000** [TASEmulators/fceux#447]
**Describe the bug**

**To Reproduce**
1. Go to https://problemkaputt.de/magicflr.htm
2.  download  https://problemkaputt.de/magicnes.zip
3. Load MAGICNES.NES

**Expected behavior**
Be able to play magic  floor
**Screenshots**
![Снимок экрана (112)](https://user-images.githubusercontent.com/8822292/149667539-3a3b265f-ecb9-42cc-8df5-acc377a9becf.png)

**(please complete the following information):**
 - OS and Version: Windows 11
 - Version of FCEUX used: 2.6.0 32bit

**Additional context**

**Comment by lonkelle** [comment]
Mapper 218 can be “changed” to 7 and still work correctly on FCEUX according to my experience. Just in case you want a quick hack.
