### ISSUE TITLE
Blue Message

### ISSUE THREAD

**Issue by LanzPal2335** [TASEmulators/fceux#448]
Those blue messages on this emulator is actually bothering me (especially for switching sides on the famicom disks). Is there a way to turn it off?
![FCEUX 2 6 1 1_20_2022 8_37_14 PM_LI](https://user-images.githubusercontent.com/98141721/150466971-2377279e-43d8-47db-a017-d39d8ca5fe5e.jpg)

**Comment by mjbudd77** [comment]
As stated,  this feature was added to the Qt GUI. It is now in the 2.6.2 release.
