### ISSUE TITLE
No sound on FreeBSD

### ISSUE THREAD

**Issue by clausecker** [TASEmulators/fceux#449]
**Describe the bug**
When compiling fceux for FreeBSD 13 and running it with any NES ROM, no audio is produced.

The `InitAudio` function fails its call to `SDL_OpenAudio` with error message

    Fragment size must be a power of two

This is because `spec.samples` is set as follows:

    spec.samples = (int)( ( (double)s_SampleRate / getBaseFrameRate() ) );

which is not guaranteed to evaluate to a power of two, a setting in violation of the [documentation](https://wiki.libsdl.org/SDL_AudioSpec), which reads: “samples specifies a unit of audio data. (...) This field's value must be a power of two.”

I have for my upcoming FreeBSD port (i.e. package in the FreeBSD Port Collection) patched this line to read

    spec.samples = 1 << (int)ceil(log2((double)s_SampleRate / getBaseFrameRate()));

instead, causing audio to be produced as expected.  Note that this patch does not guard against possible overflow of `spec.samples` (a member of type `Uint16`) which should probably be done in a proper patch.

**Comment by mjbudd77** [comment]
I made a change to force the samples to be a power of 2. Please try it out and provide feedback

**Comment by clausecker** [comment]
Yes, it works with that patch.
