### ISSUE TITLE
Hex Editor scroll bar doesn't work correctly.

### ISSUE THREAD

**Issue by flamecyclone** [TASEmulators/fceux#450]
**Describe the bug**
The scroll bar does not work properly when operating the hex editor, the data viewer and the scroll bar position are inconsistent.

**To Reproduce**
1. Drag the scroll bar up and down
2. Click the up and down buttons
3. Ctrl + A to enter the address

**Expected behavior**
1. not working correctly
2. not working correctly
3. not working correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/70200943/150623094-063910de-73ae-485b-85af-6d13ef588770.png)
https://user-images.githubusercontent.com/70200943/150629414-44abfd4b-4eb9-4a43-8002-9c4c553d3936.mp4

**(please complete the following information):**
 - Windows 10
 - QT FCEUX 2.6.1

**Additional context**
no anymore.

**Comment by mjbudd77** [comment]
I made a change which should fix this. Please try the latest dev build and let me know if it's fixed.

**Comment by flamecyclone** [comment]
ok， wait me

**Comment by flamecyclone** [comment]
But my 2.6.1 version did not reproduce, which is really strange

**Comment by flamecyclone** [comment]
But I haven't reproduced it now, it's weird

**Comment by mjbudd77** [comment]
The behavior for me before was intermittent as well. But I’m pretty sure the latest change I made will force drawing of the viewport to be where the scroll bar is set.

**Comment by mjbudd77** [comment]
@flamecyclone , can this issue be closed now?

**Comment by flamecyclone** [comment]
you can

**Comment by flamecyclone** [comment]
@mjbudd77 you can
