### ISSUE TITLE
Edit data with the hex editor does not automatically switch to the next line

### ISSUE THREAD

**Issue by flamecyclone** [TASEmulators/fceux#451]
**Describe the bug**
Edit data with the hex editor does not automatically switch to the next line

**To Reproduce**
Edit ROMs with the hex editor

**Expected behavior**
does not automatically switch to the next line

**Screenshots**
![动画](https://user-images.githubusercontent.com/70200943/150627840-ae088d4c-675c-45b1-af38-0f30e37df414.gif)

**(please complete the following information):**
Windows 10
QT

**Additional context**
Not anymore

**Comment by mjbudd77** [comment]
I have fixed this in the commit mentioned above. Please try out the latest dev build.

**Comment by mjbudd77** [comment]
@flamecyclone , are the changes working like you expect? Can we call this closed?

**Comment by mjbudd77** [comment]
This was fixed and is in the 2.6.2 release.
