### ISSUE TITLE
(feature request)

### ISSUE THREAD

**Issue by Spoopryme** [TASEmulators/fceux#452]
Allowing any hottkey to be bindable to buttons on a gamepad/controller.

**Comment by mjbudd77** [comment]
I know that the Qt port can do this already. See the gamepad config dialog and enable the advanced bindings.

**Comment by Spoopryme** [comment]
Ahhhh k I never thought to check the 'extensions' menu thank you for pointing me in the right direction this is exactly what I was looking for.
