### ISSUE TITLE
Garbled graphics in Mario Adventure romhack

### ISSUE THREAD

**Issue by despoa** [TASEmulators/fceux#455]
Running the Mario Adventure romhack on the latest version of FCEUX results in garbled graphics as shown here.

![image](https://user-images.githubusercontent.com/30417976/151828754-3b9c70d3-8712-44e5-a944-a32986283657.png)

This appears to be a regression as it shows properly on all versions of FCEUX prior to 2.5.0. Mesen also shows this properly.

The ROM tested.

Mario_Adventure.nes
CRC32: 2E6D3FDC
MD5: 326C66D832766021FCC054AE4CC4DDDF
SHA-1: 4CB0416CB8F06430EC765E0DE98B676E4183842D

**Comment by mjbudd77** [comment]
I believe this should be fixed in release 2.6.2. Please test and provide feedback

**Comment by despoa** [comment]
Appears to be fixed. Thank you.
