### ISSUE TITLE
winport shift savestate/loadstate hotkey malfunction

### ISSUE THREAD

**Issue by zeromus** [TASEmulators/fceux#456]
yuck. at some point we got a bug where holding down shift, pressing f2, then releasing shift would cause a loadstate to get triggered. broken in latest git and 2.5.0 but working in 2.3.0

**Comment by mjbudd77** [comment]
Maybe a similar issue to #402

**Comment by ClusterM** [comment]
Please try commit 8e6d99a1acd902bff1f94fbd022708567cd6647e.

**Comment by ClusterM** [comment]
Any feedback?

**Comment by vadosnaprimer** [comment]
@zeromus ^

**Comment by zeromus** [comment]
yep, fixed

**Comment by ClusterM** [comment]
> yep, fixed

Thank you
