### ISSUE TITLE
Errors with Dragon Ball 3: Gokuu Den, Akuma-Kun: Makai no Wana, and Famicom Jump: Eiyuu Retsuden

### ISSUE THREAD

**Issue by BlackPaladin2022** [TASEmulators/fceux#458]
OS & Version:  Windows 10
Applies to FCEUX 2.62

There are errors with playing the following NES/Famicom Games:

Akuma-Kun: Makai no Wana
Dragon Ball 3: Gokuu Den
Famicom Jump: Eiyuu Retsuden

With the first game, it's very severe.  The game doesn't load at all.  All I see is a black screen and nothing else.  I know the ROM is good as it works on other emulators like Mesen.

1. Load Akuma-Kun ROM

As for Dragon Ball 3: Gokuu Den, the game does load on FCE Ultra.  However, the ROM will load flashing Japanese characters in multiple colors and not run correctly.

1. Load Dragon Ball 3

Finally with Famicom Jump: Eiyuu Retsuden, the error here is the least severe compared to the three I have mentioned.  The game will run normally, but when you get to the part where you start the game in its overworld, there are graphical issues that can be distracting with the game.

1.  Load Famicom Jump: Eiyuu Retsuden
2.  Press Start to begin the game
3.  Select your character's name
4.  Scroll through introduction text
5.  Begin moving around in the overworld

![Dragon Ball 3 - Gokuu Den (Japan) (Rev 1)-0](https://user-images.githubusercontent.com/99116758/153492827-1f43abb7-d00e-4de0-9770-f6b427ab0d78.png)
![Famicom Jump - Eiyuu Retsuden (J)-0](https://user-images.githubusercontent.com/99116758/153492829-9fd02786-11c4-4472-baae-d02476abcfce.png)

**Comment by mjbudd77** [comment]
Do these games load on any previous versions of fceux?

**Comment by BlackPaladin2022** [comment]
I tested using FCEUX 2.2.3 and all three games seem to run normally using that version of the emulator, but once I test it out on FCEUX 2.3.0 and onward, the problems with those games do emerge.

**Comment by negativeExponent** [comment]
i can confirm that the games mentioned are broken in latest commit. The games in question are mapper 16, with submapper 4 which should to address at 0x6000 - 0x600D for banking and irq.

https://github.com/TASEmulators/fceux/blob/2dde684af428ded74d1fbb3b91e6d26ee6b3a125/src/boards/bandai.cpp#L306

**Comment by negativeExponent** [comment]
confirmed working now in latest commit

![1644387015_2022_02_09_14:10:15](https://user-images.githubusercontent.com/54053706/153132305-478a3969-6813-474c-a3ff-cc4b967a87a9.png)

**Comment by mjbudd77** [comment]
Are all three games good then? Can this be closed?

**Comment by BlackPaladin2022** [comment]
Is this in the released FCEUX 2.6.2 version?  If so, how was this done?  I couldn't get it running myself on that version.  How was that possible?

If this is in the interim builds, I can't check to be sure yet.  Every time I try to download that in Github or the FCEUX website, I get the following message from the download link:

_{"message":"Artifacts download limit (1024 MB/day) exceeded."}_

I can't be sure myself until I check the interim build myself.

**Comment by mjbudd77** [comment]
It is only on the interim build

**Comment by BlackPaladin2022** [comment]
> It is only on the interim build

Then I have to DL that version of FCEUX and see for myself.  I'll keep trying the link until it finally works and DL the interim build.

**Comment by g0me3** [comment]
all three are working with latest fix.
