### ISSUE TITLE
Cannot play certain dumps of Majou Densetsu 2

### ISSUE THREAD

**Issue by despoa** [TASEmulators/fceux#460]
I have found that certain dumps of Majou Densetsu 2 - Daimashikyou Galious cannot play on FCEUX 2.6.1. Testing on earlier versions of FCEUX shows that it plays fine on 2.1.2 but breaks on 2.1.3. Mesen also plays the dump just fine. Here is an example as cataloged by TOSEC.

```
Filename: Majou Densetsu 2 - Daimashikyou Galious (1987-08-11)(Konami)(JP).nes
File CRC-32: 4BB94AB2
File MD5: 63A6C9CB1CD16834DFA7FF882F7325E9
File SHA-1: F0A48F51EF3E23C26A8CDD9DF3B0EA71534154F5
ROM CRC-32: 78B09986
ROM MD5: 64E9493B942394168042645834A7F3FB
ROM SHA-1: 9FF5514C5B7D5B2D98696FAA068AAE5EDCCBC5D6

**Comment by negativeExponent** [comment]
what kind of issue? the mapper 2 code used in fceux is fine as it is. so im guessing this is yet another bad headered rom issue

![1644555046_2022_02_11_12:50:46](https://user-images.githubusercontent.com/54053706/153539377-b164c81c-c078-430f-9a98-f1602a023275.png)

**Comment by despoa** [comment]
It hangs on the grey startup screen. Did you test the ROM I specified?

**Comment by negativeExponent** [comment]
there are alot of roms floating around with bad headers and or modified or hacked. check your header, compare it to mine or just post ss of header. in any case, i still assume you have a bad headered rom, which no rom verification app like clrmame can fix or even check.

**Comment by despoa** [comment]
Here's a screenshot and an attempt to run the game on 2.6.2.

![image](https://user-images.githubusercontent.com/30417976/153566486-ac621361-203d-469c-9e90-e753c1bae037.png)

**Comment by negativeExponent** [comment]
ok noted.

Mappers 2 and 3 can have bus conflict or not. If the submapper is 2, then the rom is expected to use bus conflicts. FCEUX' has assigned bus conflicts to be enabled always for these mappars, which affects this particular game (or some variants of it).

mapper 2/3 should check if rom has ines 2.0 header and if its using submapper = 2 before enabling bus conflicts.

**Comment by mjbudd77** [comment]
I confirmed that the pull request fixed the issue.
