### ISSUE TITLE
Error with Tatakae! Rahmenman NES ROM 

### ISSUE THREAD

**Issue by BlackPaladin2022** [TASEmulators/fceux#462]
Database match: Tatakae!! Rahmen Man - Sakuretsu Choujin 102 Gei (Japan)
Database: No-Intro: Nintendo Entertainment System (v. 20210216-231042)
File SHA-1: D217E47E38BE08412FB045A1DB55A26ECA837293
File CRC32: ACC2B74A
ROM SHA-1: FFAFED6469C560790D1C158EBC980666A12477F9
ROM CRC32: C1719664

Thank you for correcting the issues with the three earlier games I had mentioned.  However, there's another Mapper 16 NES ROM that does not function, the interim build included.  (I checked with past versions of FCE Ultra, and none can run the game, unfortunately.  This game does run on both NEStopia and Mesen, however.)  When I tried running the ROM in question, the game does not run.

1.  Run Tatakae! Rahmen Man ROM.

**Comment by negativeExponent** [comment]
this game is not mapper 16. its 155 (or mapper 1 with no wram disable bit)

https://wiki.nesdev.org/w/index.php?title=INES_Mapper_155
https://nescartdb.com/profile/view/3736/tatakae-ramen-man-sakuretsu-choujin-102-gei

**Comment by BlackPaladin2022** [comment]
> this game is not mapper 16. its 155 (or mapper 1 with no wram disable bit)
> 
> https://wiki.nesdev.org/w/index.php?title=INES_Mapper_155 https://nescartdb.com/profile/view/3736/tatakae-ramen-man-sakuretsu-choujin-102-gei

My apologies.  I must have misread the dialog box in the message log.

**Comment by negativeExponent** [comment]
fceux already supports mapper 155. just change the rom's header to use mapper 155 and it should work

**Comment by BlackPaladin2022** [comment]
I got it to work!  Thank you so much!  This can be closed now.  Sorry for the inconvenience.
![Clipboard02](https://user-images.githubusercontent.com/99116758/153980875-98454f1e-25a2-420b-a201-7ff6fd730034.png)

**Comment by negativeExponent** [comment]
you should really fix all your roms first. Use this tool for windows to do so:
https://github.com/TASEmulators/fceux/issues/410#issuecomment-1034304514
make sure to install python first and this will work wonders. covers all all known roms and others.

And btw, you can close this post yourself since you are the author.
