### ISSUE TITLE
Druid: Kyoufu no Tobira (FDS) issues

### ISSUE THREAD

**Issue by BlackPaladin2022** [TASEmulators/fceux#468]
There is an issue with the FDS game, "Druid: Kyoufu no Tobira".  The game does run normally, but when playing the game, the GUI at the bottom screen while playing flickers uncontrollably.

1.  Load Druid FDS ROM
2.  Press Start Button at Title Screen
3.  Eject Disk and switch to Side B when prompted

This is found on FCEUX 2.6.2 (Windows 10). 

This is the ROM's info if needed...

Database: No-Intro: Famicom Disk System (v. 20210111-132854)
File/ROM SHA-1: 297078843E2F2302D90A5A15D446EF2F8608B0C4
File/ROM CRC32: 59E777DC

**Comment by LodanZark** [comment]
The current Druid - Kyoufu no Tobira (Japan).fds (Nintendo - Family Computer Disk System (FDS) (20220216-141427)) has the follow hashes:
SHA-1:	7b0c175a94d11db939565ad0b40dd29d6a129a5d
MD5:	bf88d1c1fc7bf0d4783859264dd6bda5
CRC32:	69139e45
