### ISSUE TITLE
sourceforge sucks, upload release files to github releases

### ISSUE THREAD

**Issue by beyondmeat** [TASEmulators/fceux#470]
It's 2022. Why do I have to go to that terrible site to get a release file :(

No insult to the dev team intended.

**Comment by vadosnaprimer** [comment]
@zeromus why can't we host them on github again?

**Comment by beyondmeat** [comment]
I think there was some strugging with tags and releases.

I know other apps solve it by using a "next" or "continuous" tag that gets replaced for every dev build.

**Comment by zeromus** [comment]
we can host them on github. desmume's doing it. only current problem is that they expire after 6 months or something like that. now that we have an example of how to set up the autobuild on desmume, someone could copy it here. but we still need to improve it to dump them all on sourceforge somehow..

**Comment by vadosnaprimer** [comment]
Releases don't expire.

**Comment by zeromus** [comment]
you can't make releases without making tags. I'm not really a fan of tagging every commit just so sourceforge will host it forever

**Comment by vadosnaprimer** [comment]
The issue is about hosting releases on github, not about hosting every commit artifact.

**Comment by zeromus** [comment]
oh. sorry.
we can put releases on github. but there's no reason to. OP's offense at having to use sourceforge doesn't motivate me. well, you and mjbudd make the releases now. you can do whatever you want.

**Comment by beyondmeat** [comment]
@zeromus you can use a "continuous" tag like https://github.com/pineappleEA/pineapple-src/tree/continuous for master builds.

stable and beta releases on github would be satisfy my request, although I do like nightly/master builds. Do those really need to live forever though?

**Comment by zeromus** [comment]
So who re-tags every single commit as continuous?

**Comment by beyondmeat** [comment]
github actions. You shouldn't be needing to do anything manually.
https://github.com/softprops/action-gh-release

I'm not too familiar with the specifics but I'm sure pineappleEA people will be happy to answer any questions about how they do it. They are making a release build for every commit automated.

**Comment by zeromus** [comment]
someone needs to find the issue on desmume where this has been discussed and mention this there as something to try
yes, I'm really so busy I can't do that
