### ISSUE TITLE
FCEUX 2.6.4: MAP126, MAP215 Support

### ISSUE THREAD

**Issue by SopTheSop27** [TASEmulators/fceux#479]
Add MAP126, MAP215 Support

**Comment by negativeExponent** [comment]
mapper 126 indeed needs to be updated to latest, but what are you specifically requesting for mapper 215? The only thing i see missing is to identify submapper 1 rom which is available as UNIF-8327A rom anyways.

**Comment by SopTheSop27** [comment]
Mapper 126 Is Used On PowerJoy 84-in-1 (PJ-008) (Unl) [!]. Mapper 215 Is Used On Super 308 3-in-1 (Unl) [!].
![Screenshot_20220313-222217~2](https://user-images.githubusercontent.com/101358042/158079975-c9abef88-4bb8-46c9-a49d-3c46f468a6b5.jpg)
![Screenshot_20220313-222317~2](https://user-images.githubusercontent.com/101358042/158079978-4795c5f9-0ccd-4b2c-b572-4a05e8e7167f.jpg)

**Comment by negativeExponent** [comment]
Mapper 215: Looks fine to me

![1647214546_2022_03_14_07:35:46](https://user-images.githubusercontent.com/54053706/158084239-63b0a3b9-7ca5-4b80-8775-5d8154a8a8ea.png)

**Comment by SopTheSop27** [comment]
Mapper 126:
