### ISSUE TITLE
iNES Header Editor mapper index incorrect

### ISSUE THREAD

**Issue by negativeExponent** [TASEmulators/fceux#480]
**Describe the bug**
Initial mapper info is incorrect.

**To Reproduce**
* Load a mapper 21 rom file.
* Click Debug > iNES header editor.
* this will show Mapper 22 instead of mapper 21

**Expected behavior**
should show the correct mapper used in current rom file loaded

**Screenshots**

**(please complete the following information):**
 - OS and Version: [e.g. Windows 10]
 linux (arch)
 - Version of FCEUX used (QT or non-QT)
 Qt

**Additional context**
roms 0-19 shows correct correctr initial mapper number when loaded in ines header editor
roms 21 and above shows incorrect index

**Comment by mjbudd77** [comment]
I pushed a commit that I believe will fix this. Please try it out and provide feedback.

**Comment by negativeExponent** [comment]
look ok now. thanks
