### ISSUE TITLE
FCEUX 2.6.5: VT01, VT02, VT03, VT09 Support

### ISSUE THREAD

**Issue by SopTheSop27** [TASEmulators/fceux#481]
Add Support For VT01, VT02, VT03, VT09. Also .nesm & .bin Format Support
![Triple-vt03-title](https://user-images.githubusercontent.com/101358042/159937194-d6333054-2181-409a-a0e3-b32d0664b817.png)
![Tetris_(NES,_VT03)-speedmenu](https://user-images.githubusercontent.com/101358042/159937260-5a828673-2343-4901-a7ec-03de901bce90.png)
![Vt01](https://user-images.githubusercontent.com/101358042/159937284-707eec06-6756-4bd0-8a76-4dbc39020e76.png)
![maxresdefault~3](https://user-images.githubusercontent.com/101358042/159937314-e1921320-b535-41fa-aa22-6762429b55a0.jpg)

**Comment by Squidward22** [comment]
It requires to add .bin, .wxn, .nesm FILE EXTENSION for VT03 support
