### ISSUE TITLE
Add Famicom Sound Expansion On/Off In Audio Options

### ISSUE THREAD

**Issue by ghost** [TASEmulators/fceux#490]
**FDS** Sound Expansion On/Off

**VRC6** Sound Expansion On/Off

**MMC5** Sound Expansion On/Off

**VRC7** Sound Expansion On/Off

**N163** Sound Expansion On/Off

**S5B** Sound Expansion On/Off

**Comment by vadosnaprimer** [comment]
Duplicate of #483
