### ISSUE TITLE
QT Win64 debugger buttons/keyboard shortcuts don't match with function

### ISSUE THREAD

**Issue by SonnyJim** [TASEmulators/fceux#491]
**Describe the bug**
When I press 'Run Line' or F7, instead of running one line it runs 128.  If I press 'Step Over' it runs one line.  Looks like an off-by-one error somewhere.

**To Reproduce**
Start ROM
Open debugger
press 'Pause' button
Press 'Run line' or press F7

**Expected behavior**
It should run 1 line then stop, instead it goes 128 lines
 - OS and Version: [e.g. Windows 10]
 - Win 10 FCEUX 2.6.4 QT

**Comment by mjbudd77** [comment]
Run line actually means run one PPU scan line.

**Comment by SonnyJim** [comment]
Ah my mistake.  I'll learn to read the documentation before opening bugs ;)
