### ISSUE TITLE
Why does FCEUX show a gray screen when running on headless linux?

### ISSUE THREAD

**Issue by ZhihangDeng** [TASEmulators/fceux#493]
I use ssh to connect to headless Linux and use x11 to run GUI programs like Firefox. When I run FCEUX, though, I get a gray screen.
![_%07Y(O7IFOZ)D{SYT~M)SO](https://user-images.githubusercontent.com/65417572/164972460-f13bc949-72a3-4b3c-86cf-25de1ab54765.png)
![IPI4CYAQNM{RUBC2XP`V05W](https://user-images.githubusercontent.com/65417572/164972468-09fbc890-d222-42f7-90d1-88feff505680.png)

**Comment by mjbudd77** [comment]
Fceux for Linux uses Qt for the GUI. I believe Qt GUI applications require a connection to an X server.

**Comment by ZhihangDeng** [comment]
Absolutly, but how to create a connection to the local x server for Fceux?

**Comment by ZhihangDeng** [comment]
I have tried many programs outside of Fceux, such as xclock, xeyes, and they all work fine.

**Comment by mjbudd77** [comment]
I couldn’t tell you why it doesn’t work. I’m having trouble understanding your motivation to run over an ssh connection. The Qt port is cross platform and should run natively on whatever OS you are running natively. So why use the remote connection?

**Comment by zeromus** [comment]
Do xclock, xeyes, and they all use qt? A comparison to non-qt apps is not useful. If you have this problem with all qt apps then this is a question for your desktop vendor or qt

**Comment by thor2016** [comment]
I see that others have posted on the Qt forum with similar questions. https://forum.qt.io/topic/79580/opening-qt-from-remote-desktop-connection  I would try there. Either way, this is not something that we have control over.
