### ISSUE TITLE
Memory Watch prefixes are broken because of input sanitation

### ISSUE THREAD

**Issue by Drakim** [TASEmulators/fceux#496]
**Describe the bug**
The input sanitation of Memory Watch addresses prevents me from adding prefixes to format the value as explained in the FCEUX help manual. This misguided input sanitation locks the functionality away. I tried getting around it by editing the external "Memory address list" with a text editor, but unfortunately FCEUX converts all addresses to upper case, making my address x0198 into X0198 which has a different meaning.

**To Reproduce**
1. Open Memory Watch
2. Click in the first Address textbox
3. Type "x"
4. Error pops up saying "You can only type characters for hexadecimal numbers (0-9,A-F)"

**Expected behavior**
There should be no input sanitation on the Address textbox, adding it was a mistake as it's not purely used for hex values. It should also not upper case the addresses when reading them from an external file, as the casing has an impact on the syntax.

**Screenshots**
![image](https://user-images.githubusercontent.com/7129377/166144788-716f017c-d879-40ce-b685-77cdbccfa9ce.png)

![image](https://user-images.githubusercontent.com/7129377/166144497-920cd945-1c9a-4816-8873-f12c58172afc.png)

**Info**
 - OS and Version: Windows 10 Pro, version 21H2
 - Version of FCEUX used (QT or non-QT): FCEUX 2.6.4 win32 Binary, non-QT

**Comment by zeromus** [comment]
OK, I fixed this, but I don't like how these boxes micromanage your input. For example you can't select all that text easily to make normal edits like in any other edit box. I have never liked that behavior in any program. The UI should just display something in red ERROR when you have invalid contents. But I checked back to fceux 2.2.2 and it had been that way for a while so I decided to leave it. If someone wanted to take custody of this and change it to work the way I prefer, I wouldn't complain. In the meantime this does now at least work the way it was intended to.
