### ISSUE TITLE
Cannot compile on Fedora 35: fatal error: unzip.h: No such file or directory

### ISSUE THREAD

**Issue by thanasisk** [TASEmulators/fceux#497]
**Describe the bug**
Cannot compile on Fedora 35

**To Reproduce**
inside `./build`:
`cmake  -DCMAKE_INSTALL_PREFIX=/usr  -DCMAKE_BUILD_TYPE=Release  ..`
```
-- GUI Frontend: Qt5
-- OpenGL preference: LEGACY
-- Using System minizip 3.0.2
-- Checking for module 'x264'
--   Package 'x264', required by 'virtual:world', not found
-- Checking for module 'x265'
--   Package 'x265', required by 'virtual:world', not found
-- Checking for modules 'libavcodec;libavformat;libavutil;libswresample;libswscale'
--   Package 'libavcodec', required by 'virtual:world', not found
--   Package 'libavformat', required by 'virtual:world', not found
--   Package 'libavutil', required by 'virtual:world', not found
--   Package 'libswresample', required by 'virtual:world', not found
--   Package 'libswscale', required by 'virtual:world', not found
-- Has X11 Library 1.7.3.1
-- Checking for module 'xkbcommon'
--   Package 'xkbcommon', required by 'virtual:world', not found
-- Checking for one of the modules 'lua5.1;lua-5.1'
-- Using Internal Lua
-- Using System zlib 1.2.11
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lxt/deleteme/fceux-2.6.4/build
```
once this is done:
`make` setting `nproc` as needed
after a bit of compilation:
```
fceux-2.6.4/src/drivers/Qt/AboutWindow.cpp:26:10: fatal error: unzip.h: No such file or directory
   26 | #include <unzip.h>
      |          ^~~~~~~~~
compilation terminated.
```
even though both `zlib-devel` and `minizip-devel` are on the system and detected from CMake.

**Expected behavior**
Compile, given the mandatory dependencies are met.

**Screenshots**
N/A

**(please complete the following information):**
 - OS and Version: [Fedora Linux 35]
 - Version of FCEUX used (QT)

**Additional context**
N/A

**Comment by mjbudd77** [comment]
Looks like it is having trouble finding a minizip header file. RPM fusion has a fully functional build on fedora 35. Look in the fceux.spec file for rpm fusion to see how they build it. Also maybe try installing the package minizip-compat-devel

**Comment by thanasisk** [comment]
thanks, I followed the instructions contained within `fceux.spec` from RPM fusio and I was able to compile. Issue solved.
