### ISSUE TITLE
Garbled graphics in some NES Games

### ISSUE THREAD

**Issue by ghost** [TASEmulators/fceux#502]
Is is possible to fix garbled graphics on some NES Games.

I found Garbled graphics on some NES Games including Mario 7-in-1 (Mapper 52) [p1][!] & Mario 7-in-1 (Mapper 52) [!] Games, ect:

2. Mario 5
4. Mario 10
7. Mario 7

Mario 5:
![Mario 7-in-1 (Mapper 52)  p1 ! 000](https://user-images.githubusercontent.com/105190447/167699590-3e9c0745-866c-4b96-950d-baa2d3470fcb.png)

Mario 10:
![Mario 7-in-1 (Mapper 52)  p1 ! 001](https://user-images.githubusercontent.com/105190447/167699698-a10ce958-2b14-484a-813d-20ea88eafc70.png)
![Mario 7-in-1 (Mapper 52)  p1 ! 002](https://user-images.githubusercontent.com/105190447/167699722-65b194dd-30b1-45bd-9c45-3c23bd0244f3.png)

Mario 7:
![Mario 7-in-1 (Mapper 52)  p1 ! 003](https://user-images.githubusercontent.com/105190447/167699811-288534f0-03bb-4244-bcf0-3347f9446744.png)

But it's fine on other **Emulators**

**FIXED** (Tested on FCE Ultra (Old Version))

Mario 5:
![Mario 7-in-1 (Mapper 52)  p1 !](https://user-images.githubusercontent.com/105190447/167700019-821ac0ae-8d1a-47bc-a58c-cad79e36cd07.png)

Mario 10:
![Mario 7-in-1 (Mapper 52)  p1 !  (1)](https://user-images.githubusercontent.com/105190447/167700085-094e2c6e-84b3-4091-8776-4430486ac20d.png)
![Mario 7-in-1 (Mapper 52)  p1 !  (2)](https://user-images.githubusercontent.com/105190447/167700120-f05b581e-d5b8-4d1a-ae87-d6d58cf0cfce.png)

Mario 7:
![Mario 7-in-1 (Mapper 52)  p1 !  (3)](https://user-images.githubusercontent.com/105190447/167700167-22a082e2-edec-4f59-9539-661b424edf8e.png)

**Comment by negativeExponent** [comment]
BAD DUMP! CRC32: 0x68fe207f (wrong chr order)
GOOD DUMP! 0xb03501f2

replace your rom file.
