### ISSUE TITLE
[Qt] hex editor changes revert after reset

### ISSUE THREAD

**Issue by ClusterM** [TASEmulators/fceux#507]
**Describe the bug**
If you open hex editor, made some changes and reset game to see changes - all changes will be reverted.

**To Reproduce**
1. Open any ROM
2. Open Hex Editor
3. Change something
4. Reset game (Ctrl+R)
5. All changes are missed now

**Expected behavior**
I want to see my changes after reset, like on the Win64 version.

**(please complete the following information):**
 - Kubuntu Linux
 - QT, b912004f69c7a7ace4b709658c54340466fc1070

**Comment by zeromus** [comment]
why did you assign and unassign these, to get my attention?

**Comment by ClusterM** [comment]
> why did you assign and unassign these, to get my attention?

Just misclicked, sorry.

**Comment by thor2016** [comment]
Changed Ctrl+R mapping so that it only runs a soft reset (which should keep changes). Hard reset is now mapped to Ctrl+Shift+R. Please try latest dev build and provide feedback.

**Comment by zeromus** [comment]
ctrl+r seems to be a soft reset on the win32 version so this was probably the right way to go.

**Comment by thor2016** [comment]
I was able to come up with a good test case for this. Seems to work fine to me. I'm going to close this. Feel free to reopen if unsatisfactory.
