### ISSUE TITLE
[Qt] Focus is not changed to hex editor when opened from debuger

### ISSUE THREAD

**Issue by ClusterM** [TASEmulators/fceux#509]
**Describe the bug**
Focus is not changed to hex editor when opened from debuger when it's already open.

**To Reproduce**
1. Open any ROM
2. Open debugger
3. Right click on any line, open hex editor
4. Go back to debugger
5. Right click on any line, open hex editor
6. Hex editor window is not activated/focused

**Expected behavior**
Hex editor window should be focused again, like when it's selected from the main menu.

**(please complete the following information):**
 - Kubuntu Linux
 - Qt, b912004f69c7a7ace4b709658c54340466fc1070

**Comment by thor2016** [comment]
I believe that the merged commit mentioned above has fixed this issue.
