### ISSUE TITLE
[Qt] keyboard control does not work on non-English layouts

### ISSUE THREAD

**Issue by ClusterM** [TASEmulators/fceux#510]
**Describe the bug**
All letter keys on keyboard do not work when non-English layout is active.

**To Reproduce**
1. Open Optiopns -> GamePad config
2. Change keyboard layout to non-English (e.g. Russian or Armenian for example)
3. Try to bind any A-Z key to any button
4. There is no effect. Also if you bind keys on English layout, these keys will not work if a non-English layout is enabled.

**Expected behavior**
Letter keys on should work when non-English layout is active.

**(please complete the following information):**
 - Same problem on Kubuntu Linux and Windows 10
 - Qt, b912004f69c7a7ace4b709658c54340466fc1070

**Comment by thor2016** [comment]
ugh, I only have english keyboards, there is no way I can test new code in this area. Is non-English keyboards something that fceux normally supports?

**Comment by ClusterM** [comment]
> ugh, I only have english keyboards, there is no way I can test new code in this area. Is non-English keyboards something that fceux normally supports?

Layout != Keyboard. You can add any layout in system settings.

**Comment by ilius** [comment]
Keyboard shortcuts work in popular cross-platform browsers like Firefox and Chrome/Brave regardless of keyboard layout.
I also tested some Qt5 KDE applications (kate, kwrite, krita) in Linux, and they all seem fine (Ctrl + N or O under Persian keyboard works).

I have a lot of experience with Gtk, but very little with Qt.

**Comment by ClusterM** [comment]
Fixed via dirty hack. Tested on Windows and Linux, but more testing required.

**Comment by thor2016** [comment]
Cleaned up the hack a little by using official key code macros instead of hard coded magic numbers. So far seems to work for me. Tested on windows and linux with laptop and USB keyboards. Back up method does not work on Mac OS as QKeyEvent::nativeScanCode() doesn't return valid values.
