### ISSUE TITLE
[QT] White frame in full screen mode

### ISSUE THREAD

**Issue by ghost** [TASEmulators/fceux#514]
After switching on the force aspect ratio option and selecting, for example, PAL (11: 8), a white frame can be seen on the edges of the screen.
It is most troublesome when the default BG Side panel option is black and the game background (for example The Adams Familly) is also black. It looks a bit like the full screen mode is not extending all the way.
Win 11 Pro
Fceux 2.4.6

**Comment by thor2016** [comment]
Unfortunately, this 1-pixel border was intended as a workaround for a Qt5 issue. See the comments from the code below. 
```
// This function is needed to fix the issue referenced below. It adds a 1-pixel border
// around the fullscreen window due to some limitation in windows.
// https://doc.qt.io/qt-5/windows-issues.html#fullscreen-opengl-based-windows
QWindowsWindowFunctions::setHasBorderInFullScreen( consoleWindow->windowHandle(), true);
```

**Comment by zeromus** [comment]
This isnt a great situation. Generally we simply don't even use actual fullscreen, because it avoids problems with this. Simply make a window the size of the screen. Actual fullscreen is archaic for productivity software, only useful for games
