### ISSUE TITLE
[FCEUX 2.6.5 Update]: add Crop Overscan LEFT & RIGHT (width) for 288 lines On/Off

### ISSUE THREAD

**Issue by Squidward22** [TASEmulators/fceux#516]
Crop Overscan LEFT & RIGHT (width) for 288 lines is used on FC/NES Hardware

See:
![Super Mario Bros (W)  000](https://user-images.githubusercontent.com/105673473/170856138-18019ea3-34d4-44fa-8870-06a773090bfe.png)
![Super Mario Bros (W)  000 (2)](https://user-images.githubusercontent.com/105673473/170856142-293174a7-2496-4f9a-b39b-64b522ca4ae3.png)
![Super Mario Bros (W)  001](https://user-images.githubusercontent.com/105673473/170856146-98344a5c-6c75-4a44-9464-fb232f8d72b0.png)
![Super Mario Bros (W)  002](https://user-images.githubusercontent.com/105673473/170856150-d022653f-6d67-48f2-874c-5a45de674e25.png)
![Super Mario Bros 2 (U)  000](https://user-images.githubusercontent.com/105673473/170856159-f9bdf597-eabc-4653-9d99-8e5cc162ce22.png)
![Super Mario Bros 3 (U)  000](https://user-images.githubusercontent.com/105673473/170856161-9b7ef391-dc31-4f31-bea0-224bc21f2f65.png)
![Mega Man (USA)000](https://user-images.githubusercontent.com/105673473/170856240-bf064974-4a6a-44c7-bf84-eafb1790b50b.png)
![Mega Man 2 (USA)000](https://user-images.githubusercontent.com/105673473/170856250-1af92d4e-a138-4bba-a58b-065670f30b35.png)
![Bomberman (Japan)000](https://user-images.githubusercontent.com/105673473/170856262-c0624762-010a-4c5f-9d15-4e16772aab5f.png)

**Comment by vadosnaprimer** [comment]
> Crop Overscan LEFT & RIGHT (width) for 288 lines is used on FC/NES Hardware

Citation needed.

**Comment by ReyVGM** [comment]
Jesus christ this guy is annoying.

**Comment by Squidward22** [comment]
Not possible to add leff & right color line (Correct Aspect Ratio Lines) from NES Hardware

**Comment by Squidward22** [comment]
I said borders on sides
