### ISSUE TITLE
NES Header Editor Issue

### ISSUE THREAD

**Issue by LodanZark** [TASEmulators/fceux#519]
"iNES Header Editor" menu (under debug drop menu) should be renamed as "NES Header Editor" because "NES2.0" does not have an "i", the same way iNES doesn't have "2".

Input device $A2 is listed as "Bandai Hyper Shot" when in the reality should be named "Generic Multicart" or "Multicart" (source: https://www.nesdev.org/wiki/NES_2.0 )

**Comment by zeromus** [comment]
I cannot confirm. There's no input device $A2. $0A is Bandai Hyper Shot in our source code, for both windows and QT frontends

**Comment by LodanZark** [comment]
@zeromus Sorry, I did mean Input device $2A and not $A2, the issue it's now solved, thank you!
