### ISSUE TITLE
PowerJoy 84-in-1 (PJ-008) (Unl) [!] doesn't work

### ISSUE THREAD

**Issue by ghost** [TASEmulators/fceux#527]
[PowerJoy 84-in-1 (PJ-008) (Unl) [!]](https://drive.google.com/file/d/1F58YoZS_cvl6fnGUr7lld0U1pVqYm8cm/view?usp=drivesdk)  has issue on FCEUX

PowerJoy 84-in-1 (PJ-008) (Unl) [!] mapper is Mapper 126

It fine works on other emulators

**Comment by vadosnaprimer** [comment]
Duplicate of #479
