### ISSUE TITLE
Add stereo channel On/Off

### ISSUE THREAD

**Issue by ghost** [TASEmulators/fceux#530]
Stereo channel

Left channel: **2A03 Square 1, 2A03 Triangle, 2A03 Noise, 2A03 DPCM, 2C33 FDS, MMC5 Square 1, VRC6 Square 1, VRC6 Sawtooth, VRC7 FM1, VRC7 FM2, VRC7 FM3, N163 Wave 1, N163 Wave 2, N163 Wave 3, N163 Wave 4, S5B Square 1, S5B Square 3**

Right channel: **2A03 Square 2, 2A03 Triangle, 2A03 Noise, 2A03 DPCM, 2C33 FDS, MMC5 Square 2, VRC6 Square 2, VRC6 Sawtooth, VRC7 FM4, VRC7 FM5, VRC7 FM6, N163 Wave 5, N163 Wave 6, N163 Wave 7, N163 Wave 8, S5B Square 2, S5B Square 3**

**Comment by zeromus** [comment]
really we need a stereo mixer where all channels can be set individually at any panning

**Comment by zeromus** [comment]
I believe we have this tracked umpteen other places
