### ISSUE TITLE
add FDS (Famicom Disk System) Sound Interpolation

### ISSUE THREAD

**Issue by Squidward22** [TASEmulators/fceux#531]
@negativeExponent FDS (Famicom Disk System) Sound Interpolation means FDS Sound Emulation for example: Link no Bouken - The Legend of Zelda 2 death sound

add FDS Sound Interpolation:

> FCEUX
> REAL FDS
> EVERDRIVE N8

**Comment by vadosnaprimer** [comment]
Duplicate of #476
