### ISSUE TITLE
FCEUX 2.6.5 Updates

### ISSUE THREAD

**Issue by CraftFan23** [TASEmulators/fceux#538]
- Mapper 126 support (PowerJoy 84-in-1)
- original Famicom Disk System (2C33) sound
- EPSM sound support
- VT03 mode support
- .bin, .vxn, .nesm support file extension
- 6 sound channels On/Off (Enable/Disable) option for Famicom Expansion sound channels (FDS, MMC5, VRC6, VRC7, N163, S5B)

**Comment by ReyVGM** [comment]
You think people don't know you are the same one with multiple accounts posting the same crap?

**Comment by TheBoxGame** [comment]
O nowa wersja z tymi mapperami 2.6.5 czekam na update

**Comment by TheBoxGame** [comment]
Kiedy ktoś wypuści wersje 2.6.5 FCEUX

**Comment by CraftFan23** [comment]
@ReyVGM 
>You think people don't know you are the same one with multiple accounts posting the same crap?

I'm not the same account. I'm not posting the same shit. I requesting a FCEUX 2.6.5 Updates: Mapper 126 support, VT03 mode support, .bin, .wxn, .nesm file extension support, FCEUX Palette Color 30 (white color) should not be FCFCFC, It's supposed to be FFFFFF Palette, 6 sound channels On/Off option for Famicom Expansion sound channels (FDS, VRC6, MMC5, VRC7, S5B, N163), EPSM sound support, original Famicom Disk System 2C33 sound from real Famicom Disk System hardware
