### ISSUE TITLE
FCEUX.pal Palette 20, 30 isn't so white

### ISSUE THREAD

**Issue by ghost** [TASEmulators/fceux#540]
I found that FCEUX.pal Palette 20 and 30 is FCFCFC instead of FFFFFF palette. Is it possible to make that 20 and 30 uses **FFFFFF** (white color palette) instead of **FCFCFC**

**Comment by Yave-Yu** [comment]
You could discover FCEUX's palette uses 4x color value, so white won't FFFFFF. Just change other palette.

**Comment by zeromus** [comment]
the code should expand the bits properly from 5 to 8 so that 0x1F becomes 0xFF

**Comment by zeromus** [comment]
Arguably the old palettes are canonical now, but this doesn't change the character of the palettes really, so it's not a big deal. The checked-in FCEUX.pal hasn't been changed.
