### ISSUE TITLE
FCEUX New EXTRA EXTRA EXTRA EXTRA EXTRA SPECIAL Updates:

### ISSUE THREAD

**Issue by Creeper25** [TASEmulators/fceux#550]
--- **add Visible Sides option:** ---

The visible sides is about for example: cropping 8 pixels on sides - 240 sides. 256 is the original sides. 272, 288, 300, 320, 426, 512 are about blanking sides

- 240x240 / 240x224
![240 sides](https://user-images.githubusercontent.com/110823345/183770599-2454db5b-4104-4dc9-a257-2599a24de66f.png)
- 256x240 / 256x224 (default)
![256 sides](https://user-images.githubusercontent.com/110823345/183770604-60e73de8-c9ce-43c3-8488-dbe7af4dd5ac.png)
- 272x240 / 272x224
![272 sides](https://user-images.githubusercontent.com/110823345/183770634-31a03374-3eaf-4075-8ae5-40345cbcb90e.png)
- 288x240 / 288x224
![288 sides](https://user-images.githubusercontent.com/110823345/183770650-6ec9366f-7bb0-4859-83aa-e05fdbc524d2.png)
- 300x240 / 300x224
![300 sides](https://user-images.githubusercontent.com/110823345/183770667-676aff60-0151-491a-96ea-603f535eeaa9.png)
- 320x240 / 320x224
![320 sides](https://user-images.githubusercontent.com/110823345/183770685-b97ecd15-900b-4a20-8629-f50465b523fe.png)
- 426x240 / 426x224
![426 sides](https://user-images.githubusercontent.com/110823345/183770706-5686a207-b27c-44ad-84f4-f7f00adc1d0a.png)
- 512x240 / 512x224
![512 sides](https://user-images.githubusercontent.com/110823345/183770616-7332e5bc-4e06-44dd-81e0-7f359492da9d.png)

--- **add Famicom expansion sound channels On/Off option:** ---

- FDS On/Off
- MMC5 On/Off
- VRC6 On/Off
- VRC7 On/Off
- N163 On/Off
- S5B On/Off

--- **add VT03, VT09 mappers support** ---

VT03 & VT09 are NES Famiclone with high graphics.

File extensions: .bin, .nesm

--- **add Famicom Network System support** ---

Famicom Network System games: Super Mario Club, JRA-PAT

File extensions: .fcn

--- **Add more Mappers** ---

More Mappers from FCEUmm

**Comment by zeromus** [comment]
closing this wish list
