### ISSUE TITLE
Add Horizontal Overscan optional

### ISSUE THREAD

**Issue by MineCreeper9898** [TASEmulators/fceux#566]
Horizontal overscan shows empty areas in left & right. It uses on real NES hardware

![Horizontal Overscan](https://user-images.githubusercontent.com/111442545/187458586-695fec68-1f3e-4b73-9d36-430c760ebd01.png)

**Comment by ReyVGM** [comment]
Haven't you been told already that it's not going to happen?

**Comment by negativeExponent** [comment]
man, how many accounts has it been now...

**Comment by MineCreeper9898** [comment]
Fake accounts underaged 13. Found in [Acceptable Use Policies](https://docs.github.com/en/github/site-policy/github-acceptable-use-policies)

**Comment by SteveCraft22** [comment]
@MineCreeper9898 this is the many fake accounts you created. And you spammed the issues and pull requests 6 months ago. Stop spamming the issues and pull requests, It is prohibited activity and your account could be flagged and it is against the GitHub's [Acceptable Use Policies](https://docs.github.com/en/github/site-policy/github-acceptable-use-policies)

**Comment by MineCreeper9898** [comment]
This issue is duplicate of #516
