### ISSUE TITLE
Mac OS 10.14 Compatibility

### ISSUE THREAD

**Issue by maxoakland** [TASEmulators/fceux#571]
**Describe the bug**
FCEUX won’t run on my Mac with 10.14. I can’t find any information about a version that will run on 10.14

**To Reproduce**
1. Download on a computer with 10.14
3. Notice the crossed out icon in Finder
4. Try to open it, see that it says “Requires 10.15"

**Expected behavior**
Running in 10.14 would be very helpful

**Comment by maxoakland** [comment]
> Try installing it via homebrew.

I tried that but it gave me an error. Maybe I just don’t know how to do it right. Can you give me the correct command to enter?

**Comment by maxoakland** [comment]
It’s not an option, unfortunately. I rely on several 32-bit applications that are unsupported under 10.15

**Comment by zeromus** [comment]
Sorry, currently QT fceux for mac is a bleeding edge production. This may change some day. It may not. But we're not going to intentionally change it at this point to support an old mac.
