### ISSUE TITLE
Mapper 78's Problem

### ISSUE THREAD

**Issue by TheWithCommands** [TASEmulators/fceux#573]
**Describe the bug**
Generally, the mapper mirroring mode is single screen. If use horizontal and vertical switching modes, need to set the submapper to 3.
However, it is always in the single screen mirroring mode in this emulator and will not change depending on whether the submitter is 3.

**Screenshots**
![mesen](https://user-images.githubusercontent.com/67952504/193851806-13f12c95-337e-4a31-a842-100db500f40e.png)
Mesen's Performance
![fceux](https://user-images.githubusercontent.com/67952504/193852988-7622f7ba-fcce-4d88-8b1d-264bc21a5012.png)
FCEUX's Performance

 - OS and Version: Windows 10
 - Version of FCEUX used: 2.6.4

**Comment by negativeExponent** [comment]
currently, mapper does not take into account submappers(like most of the current mapper implementations for now).
