### ISSUE TITLE
Add Show Horizontal Overscan On/Off

### ISSUE THREAD

**Issue by EmuCraft99** [TASEmulators/fceux#575]
@chrisledet @Invariel @zeromus @iamgreaser @tomzx @negativeExponent @vadosnaprimer 

Can you please add Show Horizontal Overscan option. This would to show empty areas (borders/background color/blank areas). **280px width** from NTSC NES/Famicom hardware

Screenshot example:
![External](https://user-images.githubusercontent.com/115377579/194730312-87629fe2-4252-433b-8463-856607da08fe.png)

**Comment by vadosnaprimer** [comment]
You don't need horizontal overscan for that. If the time you've spent on spamming out issue tracker with this, was instead spent on looking at fceux video config, you'd have noticed that you can do this

![изображение](https://user-images.githubusercontent.com/7092625/194743945-696e9efb-bdd6-4ee6-800a-770be31e0e2a.png)

by manually resizing the window, while having these settings

![изображение](https://user-images.githubusercontent.com/7092625/194743975-e45877e5-f8dc-4030-884d-952f9ea310ae.png)

**Comment by negativeExponent** [comment]
i dont think this is available in the QT ui, you can resize the window while maintaining game's aspect but there's is not way to add background color around it.

![1665306784_2022_10_09_17:13:04](https://user-images.githubusercontent.com/54053706/194748432-ccf88d34-4a76-4fe2-9f3e-2dea61052d28.png)

**Comment by vadosnaprimer** [comment]
A missing feature then, and it makes perfect sense to request BG color filling there.

**Comment by thor2016** [comment]
I just added this missing feature to Qt GUI. The Qt GUI previously only had a color picker for choosing a static color for the extra space in the video window. It was accessed via the options submenu on the main menu bar. I added a checkbox to optionally enable using the palette BG color instead of the statically chosen color.
