### ISSUE TITLE
Game Genie Encoder/Decoder Add To Cheatlist Doesn't Actually Update The Cheatlist To Show The Code

### ISSUE THREAD

**Issue by cyperium** [TASEmulators/fceux#579]
When making a Game Genie code from the Game Genie Encoder/Decoder and then adding the code to the cheatlist while the Cheat Search window is visible, the cheatlist isn't updated with the code, clicking the Update button doesn't work. Instead when you click the Add button in the cheatlist to add the cheat specified in the textboxes above the button, the code from the Game Genie Encoder/Decoder shows up in the list together with the cheat that you newly added.

To replicate:
1: Have both the Game Genie Encoder/Decoder window and the Cheat Search window open
2: Create any GG code by filling in the address, value and compare values.
3: Click Add To Cheatlist.

**Comment by cyperium** [comment]
Closing the Cheat Search window and opening it again shows the code, but that is pretty inconvenient and clearly not how it's supposed to work (also didn't work like that in the version I had a year ago).

**Comment by thor2016** [comment]
Fixed in commit reference above.
