### ISSUE TITLE
[Question] How to disable drawing text and icon in game canvas?

### ISSUE THREAD

**Issue by ghostplant** [TASEmulators/fceux#581]
How to disable drawing text and icon in game canvas? e.g. "Save/Load Notification", "Movie Recording Circle", etc? Where is the code file to change that?

**Comment by zeromus** [comment]
There's no "hide OSD" option to control it, generally, although there may be for the case of "movie recording circle".

This is all in drawing.cpp. See  DrawMessage() for example. you will have to add checks for a global "hide OSD" option in several places.
