### ISSUE TITLE
Add more features

### ISSUE THREAD

**Issue by ghost** [TASEmulators/fceux#586]
@chrisledet @Invariel @zeromus @iamgreaser @tomzx @negativeExponent @vadosnaprimer 
Can you please add features:

VRC7 - Replace VRC7 with YM2413 (OPLL) on/off
MMC5 - Non-linear channel mixer on/off
MMC5 - Reset phase counter on/off
N163 - Serial multiplex mixing on/off
N163 - Write Protect Phase on/off
N163 - Limit Wavelenght on/off
FDS - Lowpass Filter Cutoff on/off
FDS - $4085 resets modulator phase on/off
FDS - Write Protect $8000-$DFFF on/off
APU - Non-linear channel mixer on/off
APU - Reverse bits of DPCM on/off

**Comment by zeromus** [comment]
why?

**Comment by SopTheSop25B** [comment]
I found on *NSF*

**Comment by zeromus** [comment]
Error deciphering meaning from minimum effort 4 word post

**Comment by SopTheSop25B** [comment]
Features that is included on NSF
