### ISSUE TITLE
Mute Sound ?

### ISSUE THREAD

**Issue by mdnava** [TASEmulators/fceux#591]
Hello. I was previously using FCEUX v2.2.3 and there was a customizable hotkey for muting sound. 
It seems it has been removed as of v2.6.4.. Or is it still available?

I believe this is an important issue. Some ROMs explode with sound at start up.

**Comment by ReyVGM** [comment]
Just map the hotkey.

**Comment by mdnava** [comment]
> Just map the hotkey.

That's the thing.. I can't find that hotkey, which in PCEUX 2.2.3 it was available as "Sound Mute Toggle", but as of v2.6.4 I can no longer find that hotkey or any similar. Am I missing something here?.

**Comment by ReyVGM** [comment]
I can see it just fine on my end.

![New Bitmap Image](https://user-images.githubusercontent.com/7338867/211700555-75594b7b-3b4b-4b9c-8c36-d12b4e029a95.PNG)

**Comment by mdnava** [comment]
I see a different interface for hotkeys, and there's no "Sound Mute Toggle" hotkey available.

![2023-01-11 11 11 00](https://user-images.githubusercontent.com/24944618/211842222-b4cbf275-01db-4b89-9f75-bf966cc34616.png)

**Comment by ReyVGM** [comment]
I have no idea then. I just downloaded the windows version of FCEUX 2.6.4, extracted to a clean new folder and the map hotkeys menu looks exactly like the one I posted.

Try extracting it on a clean new folder and test to see which screen you see? Also, try deleting the fceux.cfg.

**Comment by vadosnaprimer** [comment]
You 2 are trying this on 2 different backends.

**Comment by thor2016** [comment]
Looks like the Qt GUI doesn't have this. I will try to add it.

**Comment by thor2016** [comment]
Sound mute feature added to Qt GUI in commit 739c01f
