### ISSUE TITLE
Breakpoint editor on Linux Qt problems

### ISSUE THREAD

**Issue by ericzx505** [TASEmulators/fceux#592]
I don't know if this is just me misunderstanding the breakpoint editor in fceux but i have a problem where i set a write or read breakpoint but when the address is either written to or read from nothing happens. The example i have is Mega Man 3 and the address that is used to store lives. This is address $18AE of the CPU memory.

Here i set the breakpoint for either read or write
![haha1](https://user-images.githubusercontent.com/51841858/206928865-bfeda959-1003-4885-a186-d40190338158.png)

Then i die to have the value changed and it doesn't break
![haha](https://user-images.githubusercontent.com/51841858/206928911-37e23ca8-a29c-48d7-8ce7-e10827dd4ed9.png)

This might be something I'm misunderstanding with the breakpoint editor but that should stop the emulation, no?

**Comment by vadosnaprimer** [comment]
Does it work well in the win32 version? Should work in Wine.

**Comment by ericzx505** [comment]
> The address $18AE falls in the mirrored RAM area of the memory map. I think the address you are actually looking for is $00AE.

Yup thats 100% what it was. I knew it was something i was misunderstood. Im new to NES debugging so thanks for the information.
