### ISSUE TITLE
Add Support playback of EPSM using any mapper

### ISSUE THREAD

**Issue by ghost** [TASEmulators/fceux#597]
@ClusterM 

[EPSM by Perkka2](https://github.com/Perkka2/EPSM) 

Is it possible to add support playback of EPSM audio expansion

[FamiStudio ROM Export EPSM - Sonic 1 OST](https://drive.google.com/file/d/1-5gzMxIZQxvjZJpt2zazwlGND0CpVFzT/view?usp=drivesdk)

**Comment by ClusterM** [comment]
Hello. Why me? I'll check but I'm not sure that is my speciality.

**Comment by SuperMarioFan2007** [comment]
Yes
