### ISSUE TITLE
Qt debugger's dbg file overwrites ld65 debug symbol file

### ISSUE THREAD

**Issue by pinobatch** [TASEmulators/fceux#600]
**Describe the bug**
Sometimes I use FCEUX, and sometimes I use Mesen. Mesen uses ld65 debug symbol files, conventionally named the same as the NES program, with `.nes` replaced with `.dbg`. It stores the list of user-added breakpoints elsewhere. FCEUX Qt stores the breakpoint list in a file named the same as the NES program, with `.nes` replaced with `.dbg`, overwriting any ld65 debug symbol file with the same name.

**To Reproduce**
1. Unzip [240p_Test_Suite_pre-0.23.zip](https://github.com/TASEmulators/fceux/files/10357428/240p_Test_Suite_pre-0.23.zip) into a new folder (or build revision 06f8ca0d5b of 240p Test Suite for NES from [source code](https://github.com/pinobatch/240p-test-mini/commit/06f8ca0d5b0281dc07abda2af36bb5dcb1073c8e))
2. Open 240pee.nes in FCEUX Qt
3. From the Debug menu, choose Debugger
4. In Breakpoints, click Add
5. Set Address to 4444
6. Check the Write checkbox
7. Click OK
8. Close FCEUX
9. Observe that 240pee.dbg is 87 bytes, not 1.4 MB as it was before

**Expected behavior**
FCEUX does not overwrite a file that is not an FCEUX debug file.

**(please complete the following information):**
 - OS and Version: Xubuntu 22.10 x86-64
 - FCEUX 2.6.5 Qt

**Additional context**
I [discussed this issue with others](https://forums.nesdev.org/viewtopic.php?p=284782#p284782) before filing it here.
- One user suggested making a copy or symlink of the NES ROM before opening it in FCEUX Qt.
- Another user suggested modifying FCEUX Qt to write `.fdb` instead of `.dbg`.

**Comment by thor2016** [comment]
Fixed in referenced commit. Qt GUI debugger save files now use a .fdb suffix.
