### ISSUE TITLE
[Feature Request] Non Tas-Editor Rewind

### ISSUE THREAD

**Issue by ReyVGM** [TASEmulators/fceux#610]
Hey guys and gals.

Right now, in order to use the rewind feature, it has to be with the TAS Editor open and as far as I could try, it only works while playing a movie.

Any chance a regular rewind feature (like it works in other emulators) could be added in a future version?

Thanks.

**Comment by thor2016** [comment]
Can you describe how this would be used? Is this so someone can rewind to a previous state and then play out from that point in time? If so, what happens when they start playing from a previous state? Are future states erased?

**Comment by ReyVGM** [comment]
States are not touched. 

I've seen other emulators do it two ways: 

1) Is to hold a key to literally "rewind" everything you did (like a fastforward, but backwards)

2) Is to make invisible states at certain intervals and press a key to jump back to those states in a reverse-chronological order.

**Comment by negativeExponent** [comment]
practically, rewind to a previous frame, not previous state. the last nth frames are saved (limited to last nth seconds for example) and you can go back to any of that point pressing whatever hotkey was assigned. any future states (not saved states) will be null and void at that point.

**Comment by thor2016** [comment]
I put together some code to do this. I called it the state recorder and added a window to the Qt GUI that allows you to configure it. You can set the total duration that it will keep recordings for, how much time in between snapshots, the compression level of each snapshot (for memory saving purposes, but comes at a performance cost), and whether or not to pause when loading a new state (supports no pause, temporary pause, and full pause). You can map hotkeys to load previous state and next state, but keep in mind that the future states are lost once it comes out of pause. By default the state recorder is off,  but you can turn it on/off from the config window and set it to auto start on new ROM loads. This is only currently in dev builds. Let me know what you think.

**Comment by ReyVGM** [comment]
Thanks for taking the time to do this, thor2016. 

I couldn't find a dev build to test it. I downloaded the interim version (fceux-win64 and  fceux-win64-QtSDL) and I couldn't find the "state recorder" option. Could you point me in the right direction?

(If it's something I need to compile myself, then let me tell you that I don't know how to do that.)

**Comment by negativeExponent** [comment]
please change or at least add a "by-frame" bases instead of by number of seconds between snapshots. tnx

tested on linux, latest commit build.

**Comment by ReyVGM** [comment]
Oh, I thought I was supposed to test it :P

**Comment by thor2016** [comment]
@negativeExponent I've added this option into the Qt GUI. You can get it from the latest dev build.
@ReyVGM only the QtSDL version will have the GUI hooks for this functionality. You can access the state recorder dialog via the main menu -> options -> state recorder config. You set the hotkeys using the hotkey config dialog. If you are a linux user you will have to build from source. If you are a windows user, the dev build is downloadable from this projects github main page (readme.md).  https://github.com/TASEmulators/fceux/releases/download/interim-build/fceux-win64-QtSDL.zip

**Comment by ReyVGM** [comment]
So this is not going to be implemented in the regular version of fceux?

I tried googling what QtSDL means, but I didn't get any satisfactory results.

Is there any benefit to using the QtSDL version over the regular version?

**Comment by thor2016** [comment]
QtSDL is just what they are calling the crossplatform version of fceux. The original win32 version was written only for windows. Qt is a cross platform GUI library and SDL (Simple DirectMedia Layer) is a cross-platform development library designed to provide low level access to audio, keyboard, mouse, joystick, and graphics hardware via OpenGL and Direct3D. Per the description on the fceux.com downloads page: The newer Qt/SDL port supports all of the features of the Win32 build (debug tools, Lua scripting, movie recording, TAS Editor). Many of the tools in the Qt/SDL port have taken on a new look and feel. There are also a few new tools exclusive to the Qt/SDL port such as the sprite viewer, NES Palette Editor, AVI RIFF Tree viewer, and frame timing tool. The Qt/SDL port is 100% cross platform and should run on any UNIX-like OS (Linux/Solaris/BSD/OSX) as well as Windows. 
You should try it, it is the only version I use. The bulk of the state recorder code is in the shared code area but the GUI window to configure/control it is only currently on the Qt version. I'm not well versed in the win32 GUI API (and I don't have time nor the motivation to learn it) but someone else could add the win32 GUI hooks if motivated to do so. But seriously, try the QtSDL version of fceux and draw your own comparisons. One thing I've noticed is that it uses separate threads for the GUI and emulation so it allows for better performance. I think the audio is a little more fluid as well.

**Comment by ReyVGM** [comment]
Thanks for the explanation and thanks for taking the time to implement this feature.

I tried it and it works as intended. I will keep using this version to see how I like it!

**Comment by thor2016** [comment]
Glad to hear it works as intended. I don't know much about the FDS emulation. It would probably be best to drop a new feature request if one does not already exist and see if someone else can help.
