### ISSUE TITLE
Building on Linux Mint

### ISSUE THREAD

**Issue by Chipsum** [TASEmulators/fceux#611]
`CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

-- GUI Frontend: Qt6
CMake Error at src/CMakeLists.txt:26 (find_package):
  By not providing "FindQt6.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt6", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt6" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "Qt6" to CMAKE_PREFIX_PATH or set "Qt6_DIR"
  to a directory containing one of the above files.  If "Qt6" provides a
  separate development package or SDK, be sure it has been installed.`

**Comment by thor2016** [comment]
This is not really an fceux issue. Its more of a Qt environment setup issue on your computer. But I will try to help. First, you must locate the location of the `Qt6Config.cmake` file on your computer. Try this command to find it:
`sudo find / -name Qt6Config.cmake`
I have Qt5 on my computer and it was found here:
`/usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake`
Once you know the directory, modify your cmake command to include the path to be something like this:
`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5 ..`
Obviously, use your path in the setting of -DCMAKE_PREFIX_PATH.

**Comment by Chipsum** [comment]
@thor2016 Thank you so much..
even after doing what you said another same error appeared demanding another Qt6 file.
Seems to be a Qt6 path problem.

**Comment by Chipsum** [comment]
After solving the Qt problem, I face now minizip, even that it's already fulfilled 

![image](https://user-images.githubusercontent.com/37517008/218809591-d46473db-2060-4763-8eff-444db8369881.png)

**Comment by thor2016** [comment]
I see that you have the minizip command line application installed, but you are missing the development files for libminizip. 
You probably need to install `libminizip-dev` or something similar.

**Comment by Chipsum** [comment]
@thor2016 Done!
Thank you so much.

**Comment by Chipsum** [comment]
Closing the issue...
![image](https://user-images.githubusercontent.com/37517008/219019907-67681886-461f-4f45-92dd-5ae8d44bc5f2.png)
