### ISSUE TITLE
What font used in OSD messages ?

### ISSUE THREAD

**Issue by Chipsum** [TASEmulators/fceux#613]
What font used in OSD messages ?

![image](https://user-images.githubusercontent.com/37517008/219127398-e3a5b7fa-9e8e-4b27-8245-62d6cf1bcd0e.png)

Other languages seems to not work with that font
![image](https://user-images.githubusercontent.com/37517008/219127875-d00f1688-f4c1-4bc0-935d-7ac30b08490e.png)

**Comment by thor2016** [comment]
I think it is a pixel bitmap defined in drawing.cpp. See the variable named Font6x7. Looks like only ascii characters with decimals values 32 <= x <= 128 are supported.

**Comment by Chipsum** [comment]
Thank you :+1:
