### ISSUE TITLE
Mapper 218 appears broken (caused by no CHR fallback on NES 2.0 header)

### ISSUE THREAD

**Issue by negativeExponent** [TASEmulators/fceux#615]
**Describe the bug**
Opening any mapper 218 causes fceux to crash

**To Reproduce**
just open any valid mapper 218 rom

**Expected behavior**
should run

**Screenshots**

**(please complete the following information):**
 - OS and Version: [e.g. Windows 10] archlinux
 - Version of FCEUX used (QT or non-QT) QT5 (master branch)

**Additional context**
tracelog: hopefully this showed anything.
https://gist.github.com/negativeExponent/3b0574aad8f099833429fe23306ef73a#file-gistfile1-txt
 tried fceux-git from aur with the same issue.

UPDATE:
Issue was cause by no CHR RAM/ROM fallback when no CHR was provided when using a NES 2.0 headered rom.

**Comment by thor2016** [comment]
I could not repro this on latest git debug build from source. Both magic floor and starfight games (use mapper 218) seem to boot fine. I'm on ubuntu 20.04 linux.

**Comment by negativeExponent** [comment]
ive already switched to Void linux and i still get the same error!

`fceux/build  🍣 master 🛤️  ×6via △ v3.25.1  took 4m36s
❯ src/fceux
Starting FCEUX 2.6.5-interim git...
NTSC mode set
NTSC mode set
Running on Platform: xcb
Emulator Start
GL Version: 3.3 (Compatibility Profile) Mesa 22.2.4 
Qt Debug: selected file path :  "/mnt/data/emulator/NES_NRS20_202212/mapper_218/Starfight.nes" (:0, )
Qt Debug: selected file path :  "/mnt/data/emulator/NES_NRS20_202212/mapper_218/Starfight.nes" (:0, )
Loading /mnt/data/emulator/NES_NRS20_202212/mapper_218/Starfight.nes...

 PRG ROM: 0 x 16KiB = 0 KiB
 CHR ROM: 0 x  8KiB = 0 KiB
 ROM CRC32: 0x00000000
 ROM MD5:  0xd41d8cd98f00b204e9800998ecf8427e
 Mapper #: 218
 Mapper name: 
 Mirroring: None (Four-screen)
 Battery-backed: No
 Trained: No
 NES2.0 Extensions
 Sub Mapper #: 0
 Total WRAM size: 0 KiB
 Total VRAM size: 0 KiB

Power on
No Debug Windows Open: Skipping loading of breakpoint data
Initializing video... Video Mode: 256 x 224 x 32 bpp 
malloc(): unaligned tcache chunk detected
zsh: IOT instruction  src/fceux`

**Comment by thor2016** [comment]
I get this when I load the game. Where did your ROM come from? 
PRG ROM: 1 x 16KiB = 16 KiB
 CHR ROM: 0 x  8KiB = 0 KiB
 ROM CRC32: 0xba00d3c1
 ROM MD5:  0x5b0680ea3bf5b3cd11fed4cf740b6068
 Mapper #: 218
 Mapper name: 
 Mirroring: None (Four-screen)
 Battery-backed: No
 Trained: No

**Comment by thor2016** [comment]
Give me a link to your ROM please. I would like to try to repro the issue.

**Comment by negativeExponent** [comment]
rom here: https://ufile.io/cf7hwspx

Im aware fceux does not support less than 16K prg variants (as the roms are only 4K size), but the 16K padded variants should work, as the same mapper code worked on fceumm.

Interestingly, if you use the Magic Floor variant from here https://problemkaputt.de/magicflr.htm (https://problemkaputt.de/magicnes.zip) first, then load the 16K rom variants from my sets, then the roms works.

**Comment by negativeExponent** [comment]
ugh.. the error was that there was no CHR RAM or ROM set as default. on iNES 1.0 header, a fallback of 8K was set. but on NES 2.0 header, some do not indicated CHR RAM/ROM on header and fceux does not  provide a fallback, hence the rom fails on load.

**Comment by thor2016** [comment]
What is the expected action here? Is a fallback guess at what the values should be really what is wanted? A hard fail right away when the header is misconfigured seems like the more desirable failure rather than it running for a bit and then potentially crashing later. Or having some other odd behavior. Maybe the GUI bailing on loading the ROM with an error message is the better way to go.

**Comment by negativeExponent** [comment]
as far as running the said roms with header indicating no chr ram/rom whatsoever, they at least run on these emus with mapper 218 support. punes for one sets a fallback of 1 8k bank of chr when headers dont provide one.

https://github.com/punesemu/puNES/blob/4084bf80b5ad067b53f3cc1bbe27de67c3abf248/src/core/ines.c#L314
https://github.com/punesemu/puNES/blob/4084bf80b5ad067b53f3cc1bbe27de67c3abf248/src/core/mappers.c#L1347

**Comment by negativeExponent** [comment]
technically,  with how Mapper 218 is implemented, it shouldn't matter if CHR was never indicated in header, it is technically just gonna be pointer to VPageR which is whats used in m218. Not entirely sure was was causing the run errors before, but my recent compiles after a system update, i can never replicated the issue again and roms run fine.

closing this issue for now.
