### ISSUE TITLE
[QT-version] PAL3x filter: custom_palette and force_grayscale don't work on-the-fly.

### ISSUE THREAD

**Issue by eugene-s-nesdev** [TASEmulators/fceux#618]
Step-by-step:
 
1. Load any ROM
2. Set "Video config" -> "Scaler" -> "PAL3x"
3. Go to "Options" -> "Palette config"
4. Try to check and uncheck "Use custom palette" and "Force Grayscale" checkboxes

Nothing happens until you reset or reload the ROM.

This bug appear in the QT-version only.
"Classic" fceux-2.6.5 (-win32 and -win64) GUI doesn't have this issue.

**Comment by thor2016** [comment]
Fixed in commit mentioned above. Feel free to re-open if fix fails.
