### ISSUE TITLE
Mapper 354 submapper 1 : Bug for B-Wings game

### ISSUE THREAD

**Issue by nb5846** [TASEmulators/fceux#621]
NES rom (mapper 354 submapper 1) : [https://forums.nesdev.org/download/file.php?id=23765](https://forums.nesdev.org/download/file.php?id=23765)

FCEUX 2.6.5-interim : Bug for this multigames rom : 2 games (the same game "B-Wings") don't work (music ok but blue screen and no gamepad) :

`71 - B WING
`
`701 - B WING I
`

**Comment by negativeExponent** [comment]
impliment CHR-RAM protect like so on Sync and the game should work...

SetupCartCHRMapping(0, CHRptr[0], CHRsize[0], (latchAddr & 8) ? 0 : 1);
