### ISSUE TITLE
[Mapper 227] Graphical bug

### ISSUE THREAD

**Issue by nb5846** [TASEmulators/fceux#625]
It seems that there is a bug for the mapper 227...
This mapper seems to work with libretro-fceumm but not with FCEUX...

Graphical bug with this rom that uses the mapper 227 : [romMulticart.nes](https://forums.nesdev.org/download/file.php?mode=view&id=24234)
(md5sum => fcd14358d45211b5887b69be3405a1be)

Warning : B-Wings game is present  (needs CHR-RAM protect ;) )

It seems that the rom was working under FCEUX 2.2.3. Is there any reason for the downgrade ?

**Comment by nb5846** [comment]
Probably, the problem is here : [addrlatch.cpp](https://github.com/TASEmulators/fceux/blob/master/src/boards/addrlatch.cpp)

`
static void M227Sync(void) {
[...]
	if ((latche & 0xF000) == 0xF000)
		SetupCartCHRMapping(0, CHRptr[0], 0x2000, 0);	
	else
		SetupCartCHRMapping(0, CHRptr[0], 0x2000, 1);
[...]
`
?

**Comment by dragon2snow** [comment]
`	if(latche & 0x080)
		SetupCartCHRMapping(0, CHRptr[0], 0x2000, 0);	
	else
		SetupCartCHRMapping(0, CHRptr[0], 0x2000, 1);`

or
`//------------------ Map 227 ---------------------------
static uint8 isbattery;
static void M227Sync(void) {
	uint32 S = latche & 1;
	uint32 p = ((latche >> 2) & 0x1F) + ((latche & 0x100) >> 3);
	uint32 L = (latche >> 9) & 1;

// ok, according to nesdev wiki (refrenced to the nesdev dumping thread) there is a CHR write protection bit7.
// however, this bit clearly determined a specific PRG layout for some game but does not meant to have additional
// functionality. as I see from the menu code, it disables the chr writing before run an actual game.
// this fix here makes happy both waixing rpgs and multigame menus at once. can't veryfy it on a hardware
// but if I find some i'll definitly do this.

	if ((!isbattery) && (latche & 0x080))
		SetupCartCHRMapping(0, CHRptr[0], 0x2000, 0);	
	else
		SetupCartCHRMapping(0, CHRptr[0], 0x2000, 1);

	if ((latche >> 7) & 1) {
		if (S) {
			setprg32(0x8000, p >> 1);
		} else {
			setprg16(0x8000, p);
			setprg16(0xC000, p);
		}
	} else {
		if (S) {
			if (L) {
				setprg16(0x8000, p & 0x3E);
				setprg16(0xC000, p | 7);
			} else {
				setprg16(0x8000, p & 0x3E);
				setprg16(0xC000, p & 0x38);
			}
		} else {
			if (L) {
				setprg16(0x8000, p);
				setprg16(0xC000, p | 7);
			} else {
				setprg16(0x8000, p);
				setprg16(0xC000, p & 0x38);
			}
		}
	}

	setmirror(((latche >> 1) & 1) ^ 1);
	setchr8(0);
	setprg8r(0x10, 0x6000, 0);
}

void Mapper227_Init(CartInfo *info) {
	isbattery = info->battery;
	Latch_Init(info, M227Sync, NULL, 0x0000, 0x8000, 0xFFFF, 1);
}
`

**Comment by negativeExponent** [comment]
pushed PR to fix CHR-RAM protect on this mapper 227. 

with regards to the sample ROM you provided for the "corrupted graphics", this said rom has invalid header, meaning no CHR size if provided. FCEUX does not provide a CHR-RAM fallback when such case exist so these no chr-size (ram or rom) in NES 2.0 header fails or appears black only.

i have opened such inquiry as how to handle such missing CHR or VROM here: 
https://github.com/TASEmulators/fceux/issues/615#issuecomment-1436180455
