### ISSUE TITLE
QT conditional breakpoint fix

### ISSUE THREAD

**Issue by fmahnke** [TASEmulators/fceux#630]
Hi, I use fceux/QT on NixOS. I noticed when I accidentally replace an existing breakpoint condition with a new, invalid condition, the original condition is removed and the breakpoint then has no condition. In this case, I want my old condition to remain so I can try my edit again. I'm proposing that as a change.

I'm working on a patch (not final) here: https://github.com/TASEmulators/fceux/compare/master...fmahnke:fceux:condition-fix?expand=1

This would be my first time contributing. I've looked around a bit on the website/code/github, and have a few questions:

Are there general guidelines for contributing?

Are there guidelines around contributing to the C++ code base? In particular, I'm wondering about formatting, tabs/spaces, and return code conventions.

Can the Windows UI be used as a guide for changes in the QT UI? I see that in the Windows debugger, an error popup is shown if a breakpoint condition fails validation. Could I assume we want the QT UI to do the same, or are there any different goals for the QT UI?

**Comment by thor2016** [comment]
I looked at your patch and found myself wondering if we should even let the user click OK on the breakpoint edit window if something is entering invalid. My thought is to make the OK button insensitive if anything entered in the window is invalid. And maybe add some sort of indication to the window to tell the user that something maybe invalid. That way the user won't have to deal with the annoyance of remaking all of their changes because they typed something in wrong.

**Comment by fmahnke** [comment]
What you suggest seems like it would be the best UX, ultimately. I didn't go any farther than I did so far because I didn't find precedent. Looks like most QT windows accept invalid data, then silently discard it. I wasn't sure if there's any plan or direction for changing that.

**Comment by thor2016** [comment]
I can't speak to all the Qt gui windows but I think alot of them have some sort of input protection. But if there are some that you know some that get annoying then we can address them on a case by case basis. I will take the action to rework the breakpoint editor window to allow for validity checks.

**Comment by fmahnke** [comment]
Ok, great. I'm using fceux debugging tools a lot this week, and see a few small issues like this. I'll submit patches as I go and we can go case by case.

**Comment by thor2016** [comment]
Is the code I've added good enough to close this?

**Comment by fmahnke** [comment]
I reviewed https://github.com/TASEmulators/fceux/commit/da7c7761a2670bc48ae86a8630903dd481b3fe27, https://github.com/TASEmulators/fceux/commit/8649a38ef9208f6ffb1cafd657be8d20879d966a, and https://github.com/TASEmulators/fceux/commit/259c5754ee2a431dd98e2fb36f057da092b2b0c1. I didn't see any problems. I also used the new breakpoint editor a couple times early in the week and it seemed to work well. Looks good to me. Thanks for doing it.
