### ISSUE TITLE
Symbol reload discards external changes

### ISSUE THREAD

**Issue by fmahnke** [TASEmulators/fceux#642]
**Describe the bug**
Debugger symbols reload doesn't respect external changes to the `.nl` files. After making a change, reloading symbols saves any changes made interactively, but overwrites any changes that were made to the files externally in the meantime. Is this the intended behavior? I'd expect the opposite.

**To Reproduce**

1. Open ROM and debugger
2. Make any change to one of the ROM's `.nl` symbol files outside of the program.
3. Click Symbols: Reload

The external change is overwritten.
 
**Expected behavior**
I'd expect the exact opposite of what happens. External changes are loaded into the debugger, and local changes are discarded.

 - Version `f8b8e9` (QT)

**Comment by fmahnke** [comment]
This seems to be what does it: https://github.com/TASEmulators/fceux/blob/f8b8e93eaf076a500d22e31b86b25d2b5c85692b/src/debugsymboltable.cpp#L759

We save over the symbol files before reloading them. With that line removed, it keeps external changes.

**Comment by thor2016** [comment]
Agree that this save call is not necessary. Fixed in commit [5845938](https://github.com/TASEmulators/fceux/commit/584593816f8f561c142d3b2d6f3f7c08273fb046)
