### ISSUE TITLE
Crash on macOS FCEUX 2.6.5 Qt when recording movie

### ISSUE THREAD

**Issue by fo-fo** [TASEmulators/fceux#652]
**Describe the bug**
FCEUX crashes on macOS when trying to record a .fm2 movie.

**To Reproduce**
1. Load a ROM (Ikari Warriors)
2. Choose menu Movie -> Movie Record. Choose "Now" as the starting point. Press OK.
3. FCEUX crashes.

**Expected behavior**
FCEUX shouldn't crash.

**(please complete the following information):**
 - OS and Version: macOS 13.4 (22F66)
 - FCEUX 2.6.5 Qt version

**Additional context**
I can see the following logs in the terminal:
```
Recording movie to /Users/k/.fceux/movies/Ikari Warriors (USA)-3.fm2
Movie recording started.
fceux(99569,0x7ff847f20640) malloc: *** error for object 0x7ff7b13ad0a8: pointer being freed was not allocated
fceux(99569,0x7ff847f20640) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Comment by thor2016** [comment]
I have not been able to repro this. Can you try installing the latest dev build and let me know if this is still crashing on that? https://github.com/TASEmulators/fceux/releases/download/interim-build/fceux-Darwin.dmg

**Comment by fo-fo** [comment]
> I have not been able to repro this. Can you try installing the latest dev build and let me know if this is still crashing on that? https://github.com/TASEmulators/fceux/releases/download/interim-build/fceux-Darwin.dmg

This version crashes on startup. The relevant message from the crash report seems to be:
```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/libwebp.7.dylib
Referenced from: <52CA3A26-5C77-3FD2-AA9A-C8091B8C6056> /Applications/fceux.app/Contents/Frameworks/libwebpmux.3.dylib
Reason: tried: '/Applications/fceux.app/Contents/Frameworks/../lib/libwebp.7.dylib' (no such file), '/usr/local/lib/libwebp.7.dylib' (no such file), '/usr/lib/libwebp.7.dylib' (no such file, not in dyld cache)Library not loaded: @rpath/libsharpyuv.0.dylib
Referenced from: <4D764235-01D3-3F79-83F9-5E335F8097E0> /Applications/fceux.app/Contents/Frameworks/libwebp.7.dylib
Reason: tried: '/Applications/fceux.app/Contents/Frameworks/../lib/libsharpyuv.0.dylib' (no such file), '/usr/local/lib/libsharpyuv.0.dylib' (no such file), '/usr/lib/libsharpyuv.0.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)
```

**Comment by thor2016** [comment]
I recommend trying to do a clean install of fceux using the homebrew packager. It has a separate fceux binary package for each of the currently supported MacOS versions (Sonoma, Ventura, Monterey) and has manages dependencies a little better than the Qt deployment tool does. visit here for more details: https://formulae.brew.sh/formula/fceux. Currently the auto builds here are only building for Monterey and the previous release I think was BigSur. You can also reference the fceux webpage for mac OS info: https://fceux.com/web/osx.html

**Comment by thor2016** [comment]
@fo-fo  Did you happen to try the homebrew version? I'm curious to hear if it fixes your issue.

**Comment by fo-fo** [comment]
> @fo-fo Did you happen to try the homebrew version? I'm curious to hear if it fixes your issue.

I didn't get a chance to try it yet (haven't been using FCEUX very much lately). I tried installing the homebrew version but since I have a custom `HOMEBREW_PREFIX` it wanted to build a lot of stuff from source (including GCC), so I gave up on it.

Anyway, since I haven't been using FCEUX much lately you can close this issue if you want. I might be able to give the homebrew version a new try sometime later, but can't promise anything.

**Comment by mgatto** [comment]
FWIW, I switched to the Homebrew method of installing it in Sonoma and 2.6.6 works perfectly. Before, the downloaded .dmg crashed on each startup which 2.6.4 did not do.
