### ISSUE TITLE
Feature Request: Command line option to launch in fullscreen

### ISSUE THREAD

**Issue by vanessakindell** [TASEmulators/fceux#653]
Add a command line option to start the emulator in full screen. Something along the lines of -fullscreen. This would allow easier setup of scripts for individual games to launch as if native.  A use case would be setting shell scripts as non-Steam games in Steam to launch directly into a game.

**Comment by thor2016** [comment]
This already exists in the Qt/SDL version:
`fceux -fullscreen 1`

**Comment by vanessakindell** [comment]
> This already exists in the Qt/SDL version: `fceux -fullscreen 1`

Did not know this and couldn't find it before. Awesome!
