### ISSUE TITLE
"break when exceed" in debugger doesn't work

### ISSUE THREAD

**Issue by wangsitan** [TASEmulators/fceux#654]
## Describe the bug

When I turn on the "break when exceed instructions", no matter what number was input, it would break after only 1 instruction is executed.

## To Reproduce

1. Run a game, and pause.
2. Go to debugger.
3. Turn on "break when exceed" for instructions, click "reser counters" button or not, input a number which is bigger than current instructions.
4. Click "Run" button.
5. It breaks after only 1 instruction is executed.

## Expected behavior

If the input number is 100, it should break when instructions `>` or `>=` 100.

## Screenshots
![2023-06-25 17_40_27-6502 Debugger](https://github.com/TASEmulators/fceux/assets/5144551/4f928e67-3680-4159-8202-20d3086b5964)

## other information

- OS: Windows 10
- FCEUX: 2.6.5, non-QT

**Comment by wangsitan** [comment]
I just tried other versions.
* Win64 Non-Qt 2.6.6 interim build has same problem.
* Win64 Qt 2.6.6 interim build works fine on this function.

Maybe I should turn to the Qt version  =)

**Comment by ClusterM** [comment]
Please try commit 33aca22a.

**Comment by wangsitan** [comment]
> Please try commit [33aca22](https://github.com/TASEmulators/fceux/commit/33aca22af2bb86d050717ca0bd341cd484405125).

Yeah, it works.
Thank you very much for your effort!!!
