### ISSUE TITLE
Unix version suddenly stops creating game saves.

### ISSUE THREAD

**Issue by XAUTHORITY** [TASEmulators/fceux#662]
not seeing any new saves being made on any game now at all now while I was just the other day. I did a system update today (possible that fceux got updated), I started tinkering with CLI launch options, and that is all I can think of. Here is my system info:
```
Linux 6.3.3-3-rt15-MANJARO
extra/fceux 2.6.5-2 [installed]
```
i do notice it has 2.6.5-2 above but not below.
```
Starting FCEUX 2.6.5...
Compiled with SDL version 2.26.4
Linked with SDL version 2.28.2
Compiled with QT version 5.15.8
```
Any help is welcome, I'm out of ideas. I may try next to find an older fceux package and try that.

**edit**: yeah i rolled back to 2.6.4, problem fixed - i can save games again.. maybe the repository package just got compressed with incorrect flags .. that happened to me before with another repo game .. just saying, a chance here that 2.6.5 might just be a good version for everyone else.
```
Package (1)  Old Version  New Version  Net Change
fceux             2.6.5-2           2.6.4-2            -0.07 MiB
```

**Comment by negativeExponent** [comment]
paths for save dir since the last working fceux on your end probably has changed location. i've just tried on latest master-branch and saving and loading works fine. the default dir is in ~/.fceux.

if it is indeed a compiler-related issue, then you probably would need to report that to manjaro or whatever repo that binary come from.

**Comment by thor2016** [comment]
I'm also able to save games just fine. Sounds like this issue maybe related to a specific ROM. Please provide more information.

**Comment by XAUTHORITY** [comment]
> I'm also able to save games just fine. Sounds like this issue maybe related to a specific ROM. Please provide more information.

The ROM not saving progress is Dragon Warrior 3. I recently built the latest 2.6.6-interim fceux and that same game would not save or load progress, but oddly Final Fantasy 1 could save and load progress. So less likely this is a Manjaro repo issue I think. I want to test this further but ran into issues with setting up the virtualbox VM for some reason. Emulator fceux 2.6.4 is working fine with Dragon Warrior 3.

**Comment by negativeExponent** [comment]
ive loaded DW3 with details below, and it works fine:
```
PRG ROM: 32 x 16KiB = 512 KiB
 CHR ROM: 0 x  8KiB = 0 KiB
 ROM CRC32: 0xa86a5318
 ROM MD5:  0x16a03048ce659d3d733026b6b72f2470
 Mapper #: 1
 Mapper name: MMC1
 Mirroring: Horizontal
 Battery-backed: Yes
 Trained: No
 NES2.0 Extensions
 Sub Mapper #: 0
 Total WRAM size: 8 KiB
 Total VRAM size: 8 KiB
 WRAM backed by battery: 8 KiB
 VRAM backed by battery: 0 KiB
```

![2023-08-29T09:53:02,712195964+08:00](https://github.com/TASEmulators/fceux/assets/54053706/88aff04a-bdb1-4b0b-a685-c0cc9b28063a)

**Comment by thor2016** [comment]
I'm curious how you reset the emulator. I looked into your repro case and found that I was able to get the game to create a save file when using the hard reset function (which more closely mimics a hardware reset) as opposed to the soft reset function. There was a change introduced in 2.6.5 that added separate hot keys for hard and soft NES reset functions. The default hot key mappings changed Ctrl+R to soft reset (from hard reset) and Ctrl+Shift+R changed to hard reset. I suspect this is the source of your issue. Try using the hard reset. If you don't like the default hot key assignments, they are fully configurable and you can set it back to how it used to work by just clearing the soft reset hot key and setting the hard reset hot key back to Ctrl+R.

**Comment by XAUTHORITY** [comment]
oh right if you so a soft reset then the newly created adventure log save will still be there in memory but if you totally close fceux and re-open the game it will be gone, at least in my case. i must have forgotten about that detail my mistake.

**Comment by XAUTHORITY** [comment]
at no point am I actually seeing Dragon Warrior 3 write a .sav file to disk where it does write the Final Fantasy .sav

**Comment by negativeExponent** [comment]
the only way i can replicate this is closing fceux just right after entering message even before the actual game screen appears. this way the save is created but no savegame appeared.

**Comment by thor2016** [comment]
I did just find and fix a memory leak bug in the save/load file code. The open file handles were not being closed out, which means the memory contents may not be flushed to disk properly. You may want to build from latest source and see if this helps.

**Comment by XAUTHORITY** [comment]
> I did just find and fix a memory leak bug in the save/load file code. The open file handles were not being closed out, which means the memory contents may not be flushed to disk properly. You may want to build from latest source and see if this helps.

to be clear, a "git clone" on the [main page](https://github.com/TASEmulators/fceux.git) is the way to include your new memory leak fix? I see the source on releases page is four days old.

**Comment by thor2016** [comment]
Yes, git clone is the best way to get latest source.

**Comment by XAUTHORITY** [comment]
Just tested by doing that, still no DW3 read/write while FF1 does. I will hunt down a matching gd package though the one I have is only one update behind, the rest of my packages match the current Arch Repository as of yesterday at least.
```
extra/gd 2.3.3-6 [installed]
    Library for the dynamic creation of images by programmers
```

**Comment by thor2016** [comment]
Please provide a link to the specific ROM you are using so that I can inspect it.

**Comment by XAUTHORITY** [comment]
https://file.io/ON2xLtgqA3pA is my rom i am using. i also just tried one we can both [download at archive.org](https://ia804703.us.archive.org/view_archive.php?archive=/23/items/nointro.nes/Dragon%20Warrior%20III%20%28USA%29.7z) and it does is not recognized as a valid rom format at all, no game loads. Maybe this info will lead to something useful.

**Comment by XAUTHORITY** [comment]
`extra/gd 2.3.3-6 [installed: 2.3.3-7]`
giving it another go, full repo match

**Comment by thor2016** [comment]
The ROM you provided does not have battery backed NVRAM checked in the NES header. The code will not attempt to save/load if it doesn't think the ROM has this.

**Comment by XAUTHORITY** [comment]
what tool do you use to inspect if NVRAM is present, fceux?

**Comment by XAUTHORITY** [comment]
though maybe we've come to the head of issue #662, my build commands just in case we keep going:
```
cmake  -DCMAKE_INSTALL_PREFIX=/usr  -DQT6=1  -DCMAKE_BUILD_TYPE=Debug    ..
make -j `nproc`
sudo make install
```

**Comment by XAUTHORITY** [comment]
I think I answered my own question:
```
Loading /home/yes/_games-console/``SPEEDRUN/DRAGON WARRIOR III.nes...

 PRG ROM: 32 x 16KiB = 512 KiB
 CHR ROM: 0 x  8KiB = 0 KiB
 ROM CRC32: 0xa86a5318
 ROM MD5:  0x16a03048ce659d3d733026b6b72f2470
 Mapper #: 1
 Mapper name: MMC1
 Mirroring: Horizontal
 **Battery-backed: No**
 Trained: No

```

**Comment by XAUTHORITY** [comment]
ok i'm on the hunt for a DW3 rom with a backed-battery it seems, it would be cool if I could just patch it in, any thoughts?

**Comment by XAUTHORITY** [comment]
wow i'm sorry this issue had nothing to do with fceux at all you guys, i really do appreciate you both taking time to help me figure this one out though. at least now i know one more thing to check for on new roms. crazy to me that the no-intro rom was not valid, i have had no problems with those before.

is there any way you guys know how to check an entire rom directory at one time?

**Comment by XAUTHORITY** [comment]
ask me next time you have me confused with another post. good points all around, I wonder why though the bad rom would work on 2.6.4 but not since then but that's not a big deal at all b/c it is a bad rom, no issue here, closing.
