### ISSUE TITLE
New timeStamp.cpp file renders fceux x86-only

### ISSUE THREAD

**Issue by clausecker** [TASEmulators/fceux#663]
I'm the maintainer of the FreeBSD port (package) for fceux.

I'm currently trying to update the port to 2.6.6, but had to notice that it now no longer compiles on non-x86.  This is because the new file `timeStamp.cpp` unconditionally tries to use `rdtsc`, an x86-only feature.  Previously it seems this code was guarded under the profiler option and was hence not usually built.

Please provide a code path for this module that runs on non-x86 systems or change the code so it is not required alltogether.

**Comment by thor2016** [comment]
Actually this fix will not work for @clausecker because he is using the Qt version. I have a different fix in mind. The TSC was only intended to be a debug feature for profiling. I will take care of it.

**Comment by thor2016** [comment]
@clausecker Please try patching commit d2ee635 into your build

**Comment by zeromus** [comment]
sorry I made a mess. thanks for fixing it @thor2016

**Comment by clausecker** [comment]
Works for me!
