### ISSUE TITLE
[Feature Request] Generate an executable game file

### ISSUE THREAD

**Issue by Redysz** [TASEmulators/fceux#669]
Is it possible to implement such a feature:
I have the fceux application, I have a specific ROM and I would like to generate a executable file (exe/bat/other) that will launch that particular game right away. Such a shortcut to the game. Such a function would be accessible via File -> Save game shortcut. This feature would be useful for elderly people - my mother is not very "computer literate", but if she had a desktop icon that immediately launches a particular game, she could use fceux to refresh old memories.

**Comment by ReyVGM** [comment]
Just right click on the ROM, select OPEN WITH, look for the emulator and make sure you tick to always open with that program.

Then all she has to do is double click on the rom and it will automatically load the rom with the emulator.

**Comment by thor2016** [comment]
There are ways to do this outside of the application itself. You can call the executable with the filename of the ROM  you want to open on boot. We will not be acting on this.
