### ISSUE TITLE
Warning about .fdb file

### ISSUE THREAD

**Issue by DoctorMikeReddy** [TASEmulators/fceux#673]
**Describe the bug**
Running this on an Apple Silicon macbook, I get this error:
"Warning: Failed to open file '/Users/mreddy01/Downloads/NES-ca65-example-unix/example.fdb' for reading"
Is this an issue?

**To Reproduce**
Load any nes rom file, but in this case it was running 'make test' with the sample ASM cartridge from https://github.com/bbbradsmith/NES-ca65-example

**Expected behavior**
Although this is only a warning, it seems odd to warn about a file that might not exist because the rom had not been opened before, or debugged.

**Screenshots**
Running make test:

ld65 -o example.nes -C example.cfg example.o -m example.map.txt -Ln example.labels.txt --dbgfile example.nes.dbg
fceux example.nes
timeStampModuleInit
Starting FCEUX 2.6.6...
NTSC mode set
NTSC mode set
Loading /Users/mreddy01/Downloads/NES-ca65-example-unix/example.nes...

PRG ROM: 2 x 16KiB = 32 KiB
CHR ROM: 1 x 8KiB = 8 KiB
ROM CRC32: 0xd7a25ace
ROM MD5: 0xd26a1c4258a1eb94aaa69651e792c838
Mapper #: 0
Mapper name: NROM
Mirroring: Vertical
Battery-backed: No
Trained: No

Power on
No Debug Windows Open: Skipping loading of breakpoint data
Warning: Failed to open file '/Users/mreddy01/Downloads/NES-ca65-example-unix/example.fdb' for reading
Initializing video... Video Mode: 256 x 224 x 32 bpp
Loading SDL sound with coreaudio driver...
NTSC mode set
NTSC mode set
Running on Platform: cocoa
GL Ratio: 2.000000
Emulator Start
GL Version: 2.1 Metal - 83.1
Emulator Exit

**(please complete the following information):**
 - OS and Version: MacOS 13.5.2
 - Version of FCEUX used (QT or non-QT) Qt 2.6.6

**Additional context**
None

**Comment by thor2016** [comment]
Remove warning message in commit 8600679.
