### ISSUE TITLE
Galaxian (NES ROM) does not work on FCEUX 2.6.6

### ISSUE THREAD

**Issue by BlackPaladin2022** [TASEmulators/fceux#675]
For some reason, I cannot run the NES ROM version of Galaxian on FCEUX 2.6.6.  (The FDS version of the ROM does work normally, however.)  Whenever trying to load the game with the emulator, I would receive either a blank screen or the emulator itself would close itself.  (The ROM will run effortlessly on both Mesen2 and Nestopia.)

1.  Run FCEUX
2.  File -> Open
3.  Load the Galaxian NES ROM

The game should run normally.  Instead, the game will either display a blank screen or shut down on its own without warning.

The ROMs with the following hashes were used...

Database match: Galaxian (Japan) (Rev A)
Database: No-Intro: Nintendo Entertainment System (v. 20210216-231042)
File SHA-1: C5194F07BB0960D12F6425FCA23BEB41982EDD71
File CRC32: FAB815BE
ROM SHA-1: 0FE9120FD5ADC2790B0B9E8FADD136F9C66A709F
ROM CRC32: 76A6A813

Database match: Galaxian (Japan) (Rev A)
Database: No-Intro: Nintendo Entertainment System (v. 20210216-231042)
File SHA-1: B9DA18B3FB90F51CFB6277C651E935FD28D7212A
File CRC32: A80DA263
ROM SHA-1: 0FE9120FD5ADC2790B0B9E8FADD136F9C66A709F
ROM CRC32: 76A6A813

Database match: Galaxian (Japan)
Database: No-Intro: Nintendo Entertainment System (v. 20210216-231042)
File SHA-1: A2C837C589E0FADEA7626E0245914F1B0C7948FD
File CRC32: C0B43EBF
ROM SHA-1: 44BC6C4E8B3F6C635281B4C05382E8F316D8269E
ROM CRC32: 84F61CD

This was executed on Windows 10, and the emulator used was the non-QT version of FCEUX.

**Comment by ClusterM** [comment]
👍
