### ISSUE TITLE
Emulation Speed Applied Even When Paused on Qt/SDL

### ISSUE THREAD

**Issue by TheRealQuantam** [TASEmulators/fceux#681]
The emulation speed appears to be applied even when paused in the Qt/SDL version, presumably related to screen refresh rather than emulation. If the emulation speed is high (e.g. turbo) FCEUX can use an entire CPU core even when paused. This effect seems non-linear. E.g. on my system:
1x: ~0.8% (of total CPU, which is 8 cores)
2x: ~1.1%
4x: ~1.2%
8x: ~2.2%
16x: 1-3%
20x+: 14-16% (this is maxing out one core)

If I had to take a guess without knowing anything more than what's in FCEUX options (I'm not familiar with programming SDL/Qt), I'd guess that what's happening at 20x is that the delay period becomes so small Windows can't delay that briefly so the delay gets rounded down to 0 and SDL_Delay returns immediately.

I'm guessing the correct behavior would be to cap framerate at something like 1 FPS when paused.

1. Load a ROM (in the case I measured I used Rockman (Japan) (En).nes)
2. Pause emulation
3. Turn speed up to turbo or something high

 - Windows 10 Pro 22H2 19045.3803 (latest version as of right now, but patch Tuesday is a week away)
 - FCEUX Qt 2.6.6. Also occurs on 2.6.4 and possibly earlier.

**Comment by vadosnaprimer** [comment]
Sounds like the problem bizhawk had for a while too. About 20fps when paused would be fine, tho it would depend on how many things wait for our update (for example menus locked to 1fps would be too slow).
