### ISSUE TITLE
Display bug in 2.6.6-win32

### ISSUE THREAD

**Issue by Europia79** [TASEmulators/fceux#685]
This is 2.6.6-win32:
![image](https://github.com/TASEmulators/fceux/assets/4515713/5591dc95-7ac5-45da-ab87-8e7fa91d8071)

This is 2.6.6-win64-qt:
![image](https://github.com/TASEmulators/fceux/assets/4515713/f9a5d239-2b7d-4f02-8bbd-4954aa0da480)

**Comment by vadosnaprimer** [comment]
_Config - Video - Aspect ratio - BG color_?

**Comment by Europia79** [comment]
Yes, that fixed it, TY !!!
