### ISSUE TITLE
Kubuntu 23.10 segmentation core dump on start

### ISSUE THREAD

**Issue by Blad3forc3** [TASEmulators/fceux#694]
Hi,

I get this output when running fceux when compiled from git. No errors during compile

timeStampModuleInit
Starting FCEUX 2.6.6-interim git...
NTSC mode set
NTSC mode set
Running on Platform: xcb
Segmentation fault (core dumped)

**Comment by thor2016** [comment]
I need more information. Can you provide the screen output from the cmake command you used to build from? Also, I added a script that will print the crash callstack that will help me find the problem. Please run this command from the root folder of the project:
`./scripts/linux_debug.pl`

**Comment by Blad3forc3** [comment]
I have run the script and get this:

NTSC mode set
NTSC mode set
Running on Platform: xcb

Thread 1 "fceux" received signal SIGSEGV, Segmentation fault.
QObject::objectName (this=0x0) at /usr/src/qt6-base-6.4.2+dfsg-18/src/corelib/kernel/qobject.cpp:1239
Downloading source file /usr/src/qt6-base-6.4.2+dfsg-18/src/corelib/kernel/qobject.cpp
1239        Q_D(const QObject);                                                                                                                          
1234        \sa metaObject(), QMetaObject::className()
1235    */
1236
1237    QString QObject::objectName() const
1238    {
1239        Q_D(const QObject);
1240    #if QT_CONFIG(thread)
1241        if (QThread::currentThreadId() != d->threadData.loadRelaxed()->threadId.loadRelaxed()) // Unsafe code path
1242            return d->extraData ? d->extraData->objectName.valueBypassingBindings() : QString();
1243    #endif
#0  QObject::objectName (this=0x0) at /usr/src/qt6-base-6.4.2+dfsg-18/src/corelib/kernel/qobject.cpp:1239
#1  0x0000555555788e6a in fceuStyle::fceuStyle(QStyle*) ()
#2  0x0000555555788df7 in fceuStyle::fceuStyle() ()
#3  0x0000555555718151 in consoleWin_t::consoleWin_t(QWidget*) ()
#4  0x0000555555717a54 in main ()

**Comment by thor2016** [comment]
I may have found something. Try commit [813d4c0](https://github.com/TASEmulators/fceux/commit/813d4c0c4b8358a62e9d22f41f5004a19ffc67f2) and tell me if it is fixed.

**Comment by Blad3forc3** [comment]
Just compiled now and works fine. Thanks!
