### ISSUE TITLE
Visual problems with the game Elite (1991)

### ISSUE THREAD

**Issue by YuGiOhJCJ** [TASEmulators/fceux#702]
**Details**
There are some visual problems with the game Elite (1991).

**Steps to reproduce**
1. Start FCEUX
2. Open the ROM
3. See the screen

**Expected behavior**
The full logo and the copyright notice should be shown.

**Current behavior**
Only a part of the logo is shown and the copyright notice is not visible.

**Screenshots**
Expected: https://i.imgur.com/qSFYbO5.png
Unexpected: https://i.imgur.com/oK3KvpS.png

**Additional information**
 - OS and Version: Slackware 14.2 (64-bit)
 - Version of FCEUX used: 2.2.3

**Note**
The ROM is freely available on the Ian Bell's website: http://www.elitehomepage.org/archive/a/b7120500.zip

**Comment by negativeExponent** [comment]
that rom is a PAL variant. system region should be set manually since the game do not have the correct filename indicator or a NES 2.0 header to set region automatically

**Comment by YuGiOhJCJ** [comment]
When I do:
```
$ fceux --pal ELITE.NES 
Starting FCEUX 2.2.3...
```
It is worse because I get a black screen: https://i.imgur.com/TgjQNps.png

**Comment by YuGiOhJCJ** [comment]
I close this issue.
