### ISSUE TITLE
Incorrect display of indirect addressing mode in debugger

### ISSUE THREAD

**Issue by cyneprepou4uk** [TASEmulators/fceux#729]
Started from [1843](https://github.com/TASEmulators/fceux/commit/db8fd407ab423db890d5f3352f4212999b981870) version. @TheRealQuantam please fix this,

Before on the left, current on the right.

![Снимок](https://github.com/TASEmulators/fceux/assets/59050458/888d695b-cd10-4746-93cb-854211a24844)

`,Y` must be outside the brackets.

**Comment by TheRealQuantam** [comment]
Well that was dumb. However, I'm confused. I can see why the disassembly is wrong, but I don't understand why the target address and value is wrong. Can you confirm whether the contents of $00-01 should be the same in the two screenshots?

**Comment by cyneprepou4uk** [comment]
I opened 2 different emulator versions and made a screenshot. They were not paused and not synchronized, so target address and values are whatever. Nothing wrong with that, instructions still works as intended.
