### ISSUE TITLE
SD Gundam Gaiden 2 EEPROM issues

### ISSUE THREAD

**Issue by awjackson** [TASEmulators/fceux#731]
EEPROM saving doesn't work in SD Gundam Gaiden 2. If you hexdump the 256 byte .sav file created by FCEUX, you can see that it's always completely empty, even after resting at an inn to save your game.

In an apparently related issue, when you soft reset this game, it often locks up at a black screen until you soft reset a second time.

These issues only affect this specific game; other games with X24C02 EEPROMs save properly (I tested SD Gundam Gaiden 3 and various Dragon Ball Z games)

I've done some debugging investigation, and it looks like this game is somehow programmed to support two different types of EEPROMs. The game detects which type is installed at runtime, and in FCEUX it's detecting the wrong type, which causes it to try to talk to the EEPROM using the wrong protocol. If you use a cheat or the hexeditor to change the byte at 08/9B30 (ROM offset 21B40) from D0 to 10 (changing a BNE instruction to a BPL in the EEPROM detection code) then saving will work and the game won't lock up on soft resets. Obviously this is a hack and not a real fix.

**Comment by negativeExponent** [comment]
despite my inability to read japanese, this seems to work for the related game (as far as actual writing to eeprom file). fix doesnt seem to affect mapper 157 in any matter, so its good for me!
