### ISSUE TITLE
Game Genie encoder/decoder not working properly.

### ISSUE THREAD

**Issue by calvincorrieri** [TASEmulators/fceux#738]
**Describe the bug**
I created a cheat for Micro Mages that gives you infinite lives. The memory address is 0072, and the value is 7F. The game genie encoder/decoder generated YYYAZE with those inputs. However, when I input YYYAZE into the game genie encoder/decoder, it shows a memory address of 8072. I am baffled as to why this is happening and incredibly frustrated.

**To Reproduce**
1. Create a Game Genie code using memory address 0072 and value 7F
2. Run that through the Game Genie encoder/decoder to get YYYAZE
3. Input YYYAZE into the Game Genie encoder/decoder and get memory address 8072 and value 7F.
4. Lose your mind with frustration

**Expected behavior**
I expect the YYYAZE code generated by inputting memory address 0072 and value 7F to output 0072 and 7F when YYYAZE is run back through the encoder/decoder.

**Screenshots**
I can’t really take a screenshot of this

**(please complete the following information):**
 - OS and Version: SteamOS
 - Version of FCEUX used: QT

**Additional context**
I am going insane after having spent so much time learning the necessary information to make this code just to have it not work

**Comment by dragon2snow** [comment]
https://tuxnes.sourceforge.net/gamegenie.html

0x8000-0xFFFF

**Comment by g0me3** [comment]
> https://tuxnes.sourceforge.net/gamegenie.html
> 
> 0x8000-0xFFFF

My boy.

GG for NES only access ROM area at 8000-FFFF. It even don't have a higher bit 8000 in code, so any address encoded in GG always added with 8000. Some emulators may ignore this shit and allow any address in GG code, but not this. Just use freeze memory feature in cheat engine.

**Comment by g0me3** [comment]
.
