### ISSUE TITLE
Compiled Linux executable download link

### ISSUE THREAD

**Issue by calvincorrieri** [TASEmulators/fceux#739]
Unlike the deb build, this should work on pretty much all Linux distros. I built and tested it on my Steam Deck (Arch.) You may need to install the dependencies listed here, starting at line 23. 
https://github.com/TASEmulators/fceux/blob/master/README

Link to the executable:
https://www.mediafire.com/file/yrhmdlz67y0kabc/FCEUX+Qt+2.7.0+Linux.zip/file

I hope this helps save at least one other person from the headache of having to compile it themselves. (I think it’s ridiculous that there’s still no AppImage or Flatpak release, but at least you can use this now.)

**Comment by thor2016** [comment]
The autobuild for linux is more used to catch continuous development build breaks and is really not intended for users to download and install/run. I can remove it from the download list if it is causing confusion. At this point in time, we leave packaging of official releases to the individual linux distro maintainers. For linux users who want to run with latest dev code (2.7.0 has not been officially released yet), it is not that complicated to build from source. If you want to submit a pull request that integrates building of AppImage or Flatpak executables into the appveyor autobuild system, you are welcome to do so and I will review the change. However, we will not be posting download links to builds by thirdparty users. One obvious reason is that we cannot easily vet the integrity of the executable to know is malicious content has been patched in.
